pull_request_rules:
  - name: ask to resolve conflict
    conditions:
      - -merged
      - -closed
      - conflict
    actions:
      comment:
        message: |
          This pull request is now in conflict. Could you fix it @{{author}}? 🙏
          To fixup this pull request, you can check out it locally. See documentation: https://help.github.com/articles/checking-out-pull-requests-locally/
          ```
          git fetch <remote-repo>
          git checkout -b {{head}} <remote-repo>/{{head}}
          git merge <remote-repo>/{{base}}
          git push <remote-repo> {{head}}
          ```
  - name: backport patches to 8.9 branch
    conditions:
      - merged
      - base=main
      - label=backport-8.9
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.9"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
        labels:
          - backport
  - name: backport patches to 8.8 branch
    conditions:
      - merged
      - base=main
      - label=backport-8.8
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.8"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
        labels:
          - backport
  - name: backport patches to 8.7 branch
    conditions:
      - merged
      - base=main
      - label=backport-8.7
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "8.7"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
        labels:
          - backport
  - name: backport patches to 7.17 branch
    conditions:
      - merged
      - base=main
      - label=backport-7.17
    actions:
      backport:
        assignees:
          - "{{ author }}"
        branches:
          - "7.17"
        title: "[{{ destination_branch }}] {{ title }} (backport #{{ number }})"
        labels:
          - backport
  - name: notify the backport policy
    conditions:
      - -label~=^backport
      - base=main
    actions:
      comment:
        message: |
          This pull request does not have a backport label. Could you fix it @{{author}}? 🙏
          To fixup this pull request, you need to add the backport labels for the needed
          branches, such as:
          * `backport-/d./d` is the label to automatically backport to the `/d./d` branch. `/d` is the digit
          **NOTE**: `backport-skip` has been added to this pull request.
      label:
        add:
          - backport-skip
  - name: remove backport-skip label
    conditions:
      - label~=^backport-\d
      - -merged
      - -closed
    actions:
      label:
        remove:
          - backport-skip
  - name: notify the backport has not been merged yet
    conditions:
      - -merged
      - -closed
      - author=mergify[bot]
      - "#check-success>0"
      - schedule=Mon-Mon 06:00-10:00[Europe/Paris]
      - "#assignee>=1"
    actions:
      comment:
        message: |
          This pull request has not been merged yet. Could you please review and merge it @{{ assignee | join(', @') }}? 🙏
