[[config-file-example-apache]]
= Config file example: Apache HTTP Server

++++
<titleabbrev>Apache HTTP Server</titleabbrev>
++++

Include these settings in your standalone {agent} `elastic-agent.yml` configuration file to ingest data from Apache HTTP server. 

* <<config-file-example-apache-logs>>
* <<config-file-example-apache-metrics>>

[[config-file-example-apache-logs]]
== Apache HTTP Server logs

["source","yaml"]
----
outputs: <1>
  default:
    type: elasticsearch <2>
    hosts:
      - '{elasticsearch-host-url}' <3>
    username: '${ES_USERNAME}'
    password: '${ES_PASSWORD}'
agent:
  download: <4>
    sourceURI: 'https://artifacts.elastic.co/downloads/'
  monitoring: <5>
    enabled: true
    use_output: default
    namespace: default
    logs: true
    metrics: true
inputs: <6>
  - id: {user-defined-unique-id} <7>
    name: apache-1
    type: logfile <8>
    use_output: default
    data_stream: <9>
      namespace: default
    streams:
      - id: {user-defined-unique-id} <7>
        data_stream:
          dataset: apache.access <10>
          type: logs
        paths: <11>
          - /var/log/apache2/access.log*
          - /var/log/apache2/other_vhosts_access.log*
          - /var/log/httpd/access_log*
        tags:
          - apache-access
        exclude_files:
          - .gz$
      - id: {user-defined-unique-id} <7>
        data_stream:
          dataset: apache.error <10>
          type: logs
        paths: <11>
          - /var/log/apache2/error.log*
          - /var/log/httpd/error_log*
        exclude_files:
          - .gz$
        tags:
          - apache-error
        processors:
          - add_locale: null
----

<1> For available output settings, refer to <<elastic-agent-output-configuration>>.
<2> For settings specific to the {es} output, refer to <<elasticsearch-output>>.
<3> The URL of the Elasticsearch cluster where output should be sent, including the port number. For example `https://12345ab6789cd12345ab6789cd.us-central1.gcp.cloud.es.io:443`.
<4> For available download settings, refer to <<elastic-agent-standalone-download>>.
<5> For available monitoring settings, refer to <<elastic-agent-monitoring-configuration>>.
<6> For available input settings, refer to <<elastic-agent-input-configuration>>.
<7> A user-defined unique ID to identify the input stream.
<8> For available input types, refer to <<elastic-agent-inputs-list>>.
<9> Learn about <<data-streams>> for time series data.
<10> Refer to {integrations-docs}/apache#logs[Logs] in the Apache HTTP Server integration documentation for the logs available to ingest and exported fields.
<11> Path to the log files to be monitored.

[[config-file-example-apache-metrics]]
== Apache HTTP Server metrics

["source","yaml"]
----
outputs: <1>
  default:
    type: elasticsearch <2>
    hosts:
      - '{elasticsearch-host-url}' <3>
    username: '${ES_USERNAME}'
    password: '${ES_PASSWORD}'
agent:
  download: <4>
    sourceURI: 'https://artifacts.elastic.co/downloads/'
  monitoring: <5>
    enabled: true
    use_output: default
    namespace: default
    logs: true
    metrics: true
inputs: <6>
    type: apache/metrics <7>
    use_output: default
    data_stream: <8>
      namespace: default
    streams:
      - id: {user-defined-unique-id} <9>
        data_stream: <8>
          dataset: apache.status <10>
          type: metrics
        metricsets: <11>
          - status
        hosts:
          - 'http://127.0.0.1'
        period: 30s
        server_status_path: /server-status
----

<1> For available output settings, refer to <<elastic-agent-output-configuration>>.
<2> For settings specific to the {es} output, refer to <<elasticsearch-output>>.
<3> The URL of the Elasticsearch cluster where output should be sent, including the port number. For example `https://12345ab6789cd12345ab6789cd.us-central1.gcp.cloud.es.io:443`.
<4> For available download settings, refer to <<elastic-agent-standalone-download>>.
<5> For available monitoring settings, refer to <<elastic-agent-monitoring-configuration>>.
<6> For available input settings, refer to <<elastic-agent-input-configuration>>.
<7> For available input types, refer to <<elastic-agent-inputs-list>>.
<8> Learn about <<data-streams>> for time series data.
<9> A user-defined unique ID to identify the input stream.
<10> A user-defined dataset. You can specify anything that makes sense to signify the source of the data.
<11> Refer to {integrations-docs}/apache#metrics[Metrics] in the Apache HTTP Server integration documentation for the type of metrics collected and exported fields.
