[[running-on-gke-managed-by-fleet]]
= Run {agent} on GKE managed by {fleet}

Please follow the steps to run the {agent} on <<running-on-kubernetes-managed-by-fleet>> page.

[discrete]
== Important notes:

On managed Kubernetes solutions like GKE, {agent} has no access to several data sources. Find below the list of the non-available data:

1. Metrics from https://kubernetes.io/docs/concepts/overview/components/#control-plane-components[Kubernetes control plane] components are not available. Consequently, metrics are not available for `kube-scheduler` and `kube-controller-manager`
components. In this regard, the respective **dashboards** will not be populated with data.
2. **Audit logs** are available only on Kubernetes master nodes as well, hence cannot be collected by {agent}.

== Autopilot GKE

Although autopilot removes many administration challenges (like workload management, deployment automation etc. of kubernetes clusters), additionally restricts access to specific namespaces (i.e. `kube-system`) and host paths which is the reason that default Elastic Agent manifests would not work.

Specific manifests are provided to cover **https://github.com/elastic/elastic-agent/blob/main/docs/elastic-agent-gke-autopilot.md[Autopilot environments]**.

> `kube-state-metrics` also must be installed to another namespace rather than the `default` as access to `kube-system` is not allowed.

== Additonal Resources:

- Blog https://www.elastic.co/blog/elastic-observe-gke-autopilot-clusters[Using Elastic to observe GKE Autopilot clusters]
- Elastic speakers webinar: https://www.elastic.co/virtual-events/get-full-kubernetes-visibility-into-gke-autopilot-with-elastic-observability["Get full Kubernetes visibility into GKE Autopilot with Elastic Observability"]

