[[ls-output-settings]]
= {ls} output settings

Specify these settings to send data over a secure connection to {ls}. You must
also configure a {ls} pipeline that reads encrypted data from {agent}s and sends
the data to {es}. Follow the in-product steps to configure the {ls} pipeline.

In the {fleet} <<output-settings,Output settings>>, make sure that {ls} is selected.

To learn how to generate certificates, refer to <<secure-logstash-connections>>.

[cols="2*<a"]
|===
|
[id="ls-logstash-hosts"]
**{ls} hosts**

| The addresses your {agent}s will use to connect to {ls}. Use the format
`host:port`. Click **add** row to specify additional {ls} addresses.

**Examples:**

* `192.0.2.0:5044`
* `mylogstashhost:5044`

// =============================================================================

|
[id="ls-server-ssl-certificate-authorities-setting"]
**Server SSL certificate authorities**

| The CA certificate to use to connect to {ls}. This is the CA used to generate
the certificate and key for {ls}. Copy and paste in the full contents for the CA
certificate.

This setting is optional.

// =============================================================================

|
[id="ls-client-ssl-certificate-setting"]
**Client SSL certificate**

| The certificate generated for the client. Copy and paste in the full contents
of the certificate. This is the certificate that all the agents will use to connect to {ls}.

In cases where each client has a unique certificate, the local path to that certificate can be
placed here. The agents will pick the certificate in that location when establishing a connection to
{ls}.

// =============================================================================

|
[id="ls-client-ssl-certificate-key-setting"]
**Client SSL certificate key**

| The private key generated for the client. This must be in PKCS 8 key.
Copy and paste in the full contents of the certificate key. This is the certificate key that all the agents will use to connect to {ls}.

In cases where each client has a unique certificate key, the local path to that certificate key can be placed here.
The agents will pick the certificate key in that location when establishing a connection to {ls}.

// =============================================================================

|
[id="ls-agent-proxy-output"]
**Proxy**

| Select a proxy URL for {agent} to connect to {ls}.
To learn about proxy configuration, refer to <<fleet-agent-proxy-support>>.

// =============================================================================

|
[id="ls-output-advanced-yaml-setting"]
**Advanced YAML configuration**

| YAML settings that will be added to the {ls} output section of each policy
that uses this output. Make sure you specify valid YAML. The UI does not
currently provide validation.

// =============================================================================

|
[id="ls-agent-integrations-output"]
**Make this output the default for agent integrations**

| When this setting is on, {agent}s use this output to send data if no other
output is set in the agent policy.

// =============================================================================

|
[id="ls-agent-monitoring-output"]
**Make this output the default for agent monitoring**

| When this setting is on, {agent}s use this output to send agent monitoring
data if no other output is set in the agent policy.

|===
