[[fleet-agent-proxy-support]]
= Using a proxy server

Many enterprises secure their assets by placing a proxy server between them and
the internet. The main role of the proxy server is to filter content and provide
a single gateway through which all traffic traverses in and out of a data center.
These proxy servers provide a various degree of functionality, security and
privacy.

Your organization's security strategy and other considerations may require you
to use a proxy server between some components in your deployment. For example,
you may have a firewall rule that prevents endpoints from connecting directly to
{es}. In this scenario, you can set up the {agent} to connect to a proxy, then
the proxy can connect to {es} through the firewall.

Support is available in {agent} and {fleet} for connections through HTTP Connect
(HTTP 1 only) and SOCKS5 proxy servers.

NOTE: Some environments require users to authenticate with the proxy. There are
no explicit settings for proxy authentication in {agent} or {fleet}, except the
ability to pass credentials in the URL or as keys/tokens in headers, as
described later.

Refer to <<elastic-agent-proxy-config,When to configure proxy settings>> for more
detail, or jump into one of the following guides:

* <<host-proxy-env-vars>>
* <<fleet-agent-proxy-managed>>
* <<fleet-agent-proxy-standalone>>

