[[epr-proxy-setting]]
= Set the proxy URL of the {package-registry}

{fleet} might be unable to access the {package-registry} because {kib} is
behind a proxy server.

Also your organization might have network traffic restrictions that prevent {kib}
from reaching the public {package-registry} (EPR) endpoints, like
https://epr.elastic.co/[epr.elastic.co], to download package metadata and
content. You can route traffic to the public endpoint of EPR through a network
gateway, then configure proxy settings in the
{kibana-ref}/fleet-settings-kb.html[{kib} configuration file], `kibana.yml`. For
example:

[source,yaml]
----
xpack.fleet.registryProxyUrl: your-nat-gateway.corp.net
----

If your HTTP Proxy requires authentication, you can include the 
credentials in the URI, such as `https://username:password@your-nat-gateway.corp.net`, 
only when using HTTPS.

== What information is sent to the {package-registry}?

In production environments, {kib}, through the {fleet} plugin, is the only service interacting with the {package-registry}. Communication happens when interacting with the Integrations UI, and when upgrading {kib}. The shared information is about discovery of Elastic packages and their available versions. In general, the only deployment-specific data that is shared is the {kib} version.
