[[ingest-addl-proc]]
== Additional ingest processing

You can start with {agent} and Elastic {integrations-docs}[integrations], and still
take advantage of additional processing options if you need them.

{agent} processors::
You can use link:{fleet-guide}/elastic-agent-processor-configuration.html[{agent} processors] to sanitize or enrich raw data at the source.
Use {agent} processors if you need to control what data is sent across the wire, or if you need to enrich the raw data with information available on the host.

{es} ingest pipelines::
You can use {es} link:{ref}/[ingest pipelines] to enrich incoming data or normalize field data before the data is indexed.
{es} ingest pipelines enable you to manipulate the data as it comes in. 
This approach helps you avoid adding processing overhead to the hosts from which you're collecting data.

{es} runtime fields::  
You can use {es} link:{ref}/runtime.html[runtime fields] to define or alter the schema at query time.
You can start working with your data without needing to understand how it is
structured, add fields to existing documents without reindexing your data,
override the value returned from an indexed field, and/or define fields for a
specific use without modifying the underlying schema.

{ls} `elastic_integration filter`::
You can use the {ls} link:{logstash-ref}/[`elastic_integration filter`] and
other link:{logstash-ref}/filter-plugins.html[{ls} filters] to
link:{logstash-ref}/ea-integrations.html[extend Elastic integrations] by
transforming data before it goes to {es}.
