[discrete]
[[ingest-intro]]
== Ingesting data into {es}

Bring your data!
Whether you call it _adding_, _indexing_, or _ingesting_ data, you have to get
the data into {es} before you can search it, visualize it, and use it for insights. 

Our ingest tools are flexible, and support a wide range of scenarios.
We can help you with everything from popular and straightforward use cases, all
the way to advanced use cases that require additional processing in order to modify or
reshape your data before sending it to {es}.

You can ingest:

* **General content** (data without timestamps), such as HTML pages, catalogs, and files 
* **Timestamped (time series) data**, such as logs, metrics and traces for Search, Security, Observability, or your own solution 

[ingest-best-approach]
.What's the best approach for ingesting data? 
**** 
The best choice for ingesting data is the _simplest option_ that _meets your needs_ and _satisfies your use case_.

**General content**. Choose the ingest tool that aligns with your data source.  

* To index **documents** directly into {es}, use the {es} link:{ref}/docs.html[document APIs].
* To send **application data** directly to {es}, use an link:https://www.elastic.co/guide/en/elasticsearch/client/index.html[{es}
language clients]. 
* To index **web page content**, use the Elastic link:https://www.elastic.co/web-crawler[web crawler].
* To sync **data from third-party sources**, use link:{ref}/es-connectors.html[connectors]. 
* To index **single files** for testing, use the {kib} link:{kibana-ref}/connect-to-elasticsearch.html#upload-data-kibana[file uploader].

If you would like to test things out before you add your own data, try using our {kibana-ref}/connect-to-elasticsearch.html#_add_sample_data[sample data].

**Timestamped data**. Start with {fleet-guide}[Elastic Agent] and one of the hundreds of {integrations-docs}[Elastic integrations] that are available.  
Integrations are available for many popular platforms and services, and are a good place to start. 
Check out the {integrations-docs}/all_integrations[Integration quick reference] to search for available integrations. 
If you don't find an integration for your data source, or if you need <<ingest-addl-proc,additional processing>>, we still have you covered. 
****
