[[install-uninstall-integration-assets]]
= Install and uninstall {agent} integration assets

++++
<titleabbrev>Install and uninstall integration assets</titleabbrev>
++++

{agent} integrations come with a number of assets, such as dashboards, saved
searches, and visualizations for analyzing data. When you add an integration to
an agent policy in {fleet}, the assets are installed automatically. If you're
building a policy file by hand, you need to install required assets such as
index templates.

[discrete]
[[install-integration-assets]]
== Install integration assets

. In {kib}, go to **Management > Integrations > Browse integrations**. Search for
and select an integration. You can select a category to narrow your search.

. Click the **Settings** tab.

. Click **Install <integration> assets** to set up the {kib} and {es} assets.

There are a couple of things to note about installing integration assets:

* {agent} integration assets can be installed only on a single {kib} {kibana-ref}/xpack-spaces.html[space]. If you want to access assets in a different space, you can {kibana-ref}/managing-saved-objects.html#managing-saved-objects-copy-to-space[copy them].
* It's currently not possible to have multiple versions of the same integration installed. When you upgrade an integration, the previous version assets are removed and replaced by the current version.

[discrete]
[[uninstall-integration-assets]]
== Uninstall integration assets

Uninstall an integration to remove all {kib} and {es} assets that were installed
by the integration.

. Before uninstalling an integration,
<<edit-or-delete-integration-policy, delete the integration policy>> from any
{agent} policies that use it.
+
Any {agent}s enrolled in the policy will stop using the deleted integration.

. In {kib}, go to **Management > Integrations > Installed integrations**. Search for
and select an integration.

. Click the **Settings** tab.

. Click **Uninstall <integration>** to remove all {kib} and {es} assets that
were installed by this integration.

[discrete]
[[reinstall-integration-assets]]
== Reinstall integration assets

You may need to reinstall an integration package to resolve a specific problem,
such as:

* An asset was edited manually, and you want to reset assets to their original
state.
* A temporary problem (like a network issue) occurred during package
installation or upgrade.
* A package was installed in a prior version that had a bug in the install code.

To reinstall integration assets:

. In {kib}, go to **Management > Integrations > Installed integrations**. Search for
and select an integration.

. Click the **Settings** tab.

. Click **Reinstall <integration>** to set up the {kib} and {es} assets.
