// Use these for links to issue and pulls.
:kibana-issue: https://github.com/elastic/kibana/issues/
:kibana-pull: https://github.com/elastic/kibana/pull/
:beats-issue: https://github.com/elastic/beats/issues/
:beats-pull: https://github.com/elastic/beats/pull/
:agent-libs-pull: https://github.com/elastic/elastic-agent-libs/pull/
:agent-issue: https://github.com/elastic/elastic-agent/issues/
:agent-pull: https://github.com/elastic/elastic-agent/pull/
:fleet-server-issue: https://github.com/elastic/fleet-server/issues/
:fleet-server-pull: https://github.com/elastic/fleet-server/pull/

[[release-notes]]
= Release notes

This section summarizes the changes in each release.

* <<release-notes-8.13.4>>
* <<release-notes-8.13.3>>
* <<release-notes-8.13.2>>
* <<release-notes-8.13.1>>
* <<release-notes-8.13.0>>

Also see:

* {kibana-ref}/release-notes.html[{kib} release notes]
* {beats-ref}/release-notes.html[{beats} release notes]

// begin 8.13.4 relnotes

[[release-notes-8.13.4]]
== {fleet} and {agent} 8.13.4

There are no bug fixes for {fleet} or {agent} in this release.

[discrete]
[[known-issues-8.13.4]]
=== Known issues

[[known-issue-174855-8.13.4]]
.ECS fields are not included to the `index.query.default_field` in {agent} integrations
[%collapsible]
====
*Details*

Due to changes introduced to support the ecs@mappings component template (see link:https://github.com/elastic/kibana/pull/174855[elastic/kibana/pull/174855]), {fleet} no longer includes ECS fields in the integrations' `index.query.default_field`. Not including ECS fields in the `index.query.default_field` setting may affect integrations that rely on fieldless queries (when no field is specified for a query).

If you run a query without specifying a field, the query will not return results for ECS fields.

*Impact* +

In version 8.14.0 and later, {fleet} sets `index.query.default_field` to `*`, so agentless queries will work as expected. We recommend users of {fleet} upgrade to 8.14 when that release becomes available.

If you are running 8.13.x and unable to upgrade to 8.14.0, you can follow the workarounds described in the link:https://support.elastic.co/knowledge/bbdbeb57.
====

// end 8.13.4 relnotes

// begin 8.13.3 relnotes

[[release-notes-8.13.3]]
== {fleet} and {agent} 8.13.3

Review important information about {fleet-server} and {agent} for the 8.13.3 release.

[discrete]
[[security-updates-8.13.3]]
=== Security updates

{agent}::
* Update Go version to 1.21.9. {agent-pull}4508[#4508]

[discrete]
[[known-issues-8.13.3]]
=== Known issues

[[known-issue-174855-8.13.3]]
.ECS fields are not included to the `index.query.default_field` in {agent} integrations
[%collapsible]
====
*Details*

Due to changes introduced to support the ecs@mappings component template (see link:https://github.com/elastic/kibana/pull/174855[elastic/kibana/pull/174855]), {fleet} no longer includes ECS fields in the integrations' `index.query.default_field`. Not including ECS fields in the `index.query.default_field` setting may affect integrations that rely on fieldless queries (when no field is specified for a query).

If you run a query without specifying a field, the query will not return results for ECS fields.

*Impact* +

In version 8.14.0 and later, {fleet} sets `index.query.default_field` to `*`, so agentless queries will work as expected. We recommend users of {fleet} upgrade to 8.14 when that release becomes available.

If you are running 8.13.x and unable to upgrade to 8.14.0, you can follow the workarounds described in the link:https://support.elastic.co/knowledge/bbdbeb57.
====

[discrete]
[[bug-fixes-8.13.3]]
=== Bug fixes

{fleet}::
* Fix managed agent policy preconfiguration update. ({kibana-pull}181624[#181624])
* Use lowercase dataset name in template and pipeline names. ({kibana-pull}180887[#180887])
* Fix KQL/kuery for getting {fleet-server} agent count. ({kibana-pull}180650[#180650])

{agent}::
* Fix unconditionally logging all 400 HTTP responses from {fleet-server} as API compatibility errors. {agent-pull}4481[#4481] {agent-issue}4477[#4477]
* Allow the `elastic-agent upgrade` command to succeed when the agent restarts before it has completely acknowledged the upgrade. {agent-pull}4519[#4519] {agent-issue}3890[#3890s]
* Only allow installing Elastic Defend on Windows kernels newer than 6, that is, Windows 10 /
Server 2016 and newer.
// end 8.13.3 relnotes

// begin 8.13.2 relnotes

[[release-notes-8.13.2]]
== {fleet} and {agent} 8.13.2

Review important information about {fleet-server} and {agent} for the 8.13.2 release.

[discrete]
[[known-issues-8.13.2]]
=== Known issues

[[known-issue-241-8.13.2]]
.Beats MSI binaries do not support directories with a trailing slash
[%collapsible]
====

*Details*

Due to changes introduced to support customizing an MSI install folder (see link:https://github.com/elastic/elastic-stack-installers/pull/209[#209]), Beats MSI binaries, which currently are in beta, will not properly handle directories that end in a slash. This defect may affect many deployments using the {beats} MSI binaries.

*Impact* +

This issue has been link:https://github.com/elastic/elastic-stack-installers/pull/264[resolved] in version 8.14.0 and later releases. We recommend users of {beats} MSI to upgrade to 8.14 when that release becomes available.

====

[[known-issue-174855-8.13.2]]
.ECS fields are not included to the `index.query.default_field` in {agent} integrations
[%collapsible]
====
*Details*

Due to changes introduced to support the ecs@mappings component template (see link:https://github.com/elastic/kibana/pull/174855[elastic/kibana/pull/174855]), {fleet} no longer includes ECS fields in the integrations' `index.query.default_field`. Not including ECS fields in the `index.query.default_field` setting may affect integrations that rely on fieldless queries (when no field is specified for a query).

If you run a query without specifying a field, the query will not return results for ECS fields.

*Impact* +

In version 8.14.0 and later, {fleet} sets `index.query.default_field` to `*`, so agentless queries will work as expected. We recommend users of {fleet} upgrade to 8.14 when that release becomes available.

If you are running 8.13.x and unable to upgrade to 8.14.0, you can follow the workarounds described in the link:https://support.elastic.co/knowledge/bbdbeb57.
====

[discrete]
[[bug-fixes-8.13.2]]
=== Bug fixes

{fleet}::
* Fixes having to wait ten minutes after agent upgrade if agent cleared watching state ({kibana-pull}179917[#179917]).
* Fixes using the latest available version in K8's manifest instead of the latest compatible version ({kibana-pull}179662[#179662]).
* Fixes a step in add agent instructions where a query to get all agents was unnecessary ({kibana-pull}179603[#179603]).

// end 8.13.2 relnotes

// begin 8.13.1 relnotes

[[release-notes-8.13.1]]
== {fleet} and {agent} 8.13.1

Review important information about {fleet-server} and {agent} for the 8.13.1 release.

[discrete]
[[known-issues-8.13.1]]
=== Known issues

[[known-issue-241-8.13.1]]
.Beats MSI binaries do not support directories with a trailing slash
[%collapsible]
====

*Details*

Due to changes introduced to support customizing an MSI install folder (see link:https://github.com/elastic/elastic-stack-installers/pull/209[#209]), Beats MSI binaries, which currently are in beta, will not properly handle directories that end in a slash. This defect may affect many deployments using the {beats} MSI binaries.

*Impact* +

This issue has been link:https://github.com/elastic/elastic-stack-installers/pull/264[resolved] in version 8.14.0 and later releases. We recommend users of {beats} MSI to upgrade to 8.14 when that release becomes available.

====

[[known-issue-174855-8.13.1]]
.ECS fields are not included to the `index.query.default_field` in {agent} integrations
[%collapsible]
====
*Details*

Due to changes introduced to support the ecs@mappings component template (see link:https://github.com/elastic/kibana/pull/174855[elastic/kibana/pull/174855]), {fleet} no longer includes ECS fields in the integrations' `index.query.default_field`. Not including ECS fields in the `index.query.default_field` setting may affect integrations that rely on fieldless queries (when no field is specified for a query).

If you run a query without specifying a field, the query will not return results for ECS fields.

*Impact* +

In version 8.14.0 and later, {fleet} sets `index.query.default_field` to `*`, so agentless queries will work as expected. We recommend users of {fleet} upgrade to 8.14 when that release becomes available.

If you are running 8.13.x and unable to upgrade to 8.14.0, you can follow the workarounds described in the link:https://support.elastic.co/knowledge/bbdbeb57.
====

[discrete]
[[enhancements-8.13.1]]
=== Enhancements

{fleet}::
* Remove `index.query.default_field` setting from managed component template settings. ({kibana-pull}178020[#178020])

[discrete]
[[bug-fixes-8.13.1]]
=== Bug fixes

{fleet}::
* Use index exists check in fleet-metrics-task. ({kibana-pull}179404[#179404])

// end 8.13.1 relnotes

// begin 8.13.0 relnotes

[[release-notes-8.13.0]]
== {fleet} and {agent} 8.13.0

Review important information about {fleet-server} and {agent} for the 8.13.0 release.

[discrete]
[[security-updates-8.13.0]]
=== Security updates

{agent}::
* Update Go version to 1.21.8. {agent-pull}4221[#4221]

[discrete]
[[breaking-changes-8.13.0]]
=== Breaking changes

Breaking changes can prevent your application from optimal operation and
performance. Before you upgrade, review the breaking changes, then mitigate the
impact to your application.

// copied from Kibana release notes: https://github.com/elastic/kibana/pull/179216
[discrete]
[[breaking-176879]]
.Removes conditional topics for Kafka outputs
[%collapsible]
====
*Details* +
The Kafka output no longer supports conditional topics while the final syntax is evaluated ahead of Kafka output GA. For more information, refer to ({kibana-pull}176879[#176879]).
====

// copied from Kibana release notes: https://github.com/elastic/kibana/pull/179216
[discrete]
[[breaking-176443]]
.Most Fleet installed integrations are now read-only and labelled with a *Managed* tag in the Kibana UI 
[%collapsible]
====
*Details* +
Integration content installed by {fleet} is no longer editable. This content is tagged with *Managed* in the {kib} UI, and is Elastic managed. This content cannot be edited or deleted, however managed visualizations, dashboards, and saved searches can be cloned. The clones can be customized.
When cloning a dashboard the cloned panels become entirely independent copies that are unlinked from the original configurations and dependencies. 
Managed content relating to specific visualization editors such as Lens, TSVB, and Maps, the clones retain the original reference configurations. The same applies to editing any saved searches in a managed visualization.
For more information, refer to ({kibana-pull}172393[#172393]).
====

// copied from Beats release notes: https://github.com/elastic/beats/pull/37795
[discrete]
[[breaking-37795]]
.The behavior of `queue.mem.flush.min_events` has been simplified.
[%collapsible]
====
*Details* +
The behavior of `queue.mem.flush.min_events` has been simplified. It now serves as a simple maximum on the size of all event batches. There are no longer performance implications in its relationship to `bulk_max_size`.

For more information, refer to ({beats-pull}37795[#37795]).
====

[discrete]
[[notable-changes-8.13.0]]
=== Notable changes

The following are notable, non-breaking updates to be aware of:

* Changes to features that are in Technical Preview.
* Changes to log formats.
* Changes to non-public APIs.
* Behaviour changes that repair critical bugs.

{fleet}::
* Adds reference to `ecs@mappings` for each index template ({kibana-pull}174855[#174855]).

[discrete]
[[known-issues-8.13.0]]
=== Known issues

[[known-issue-241-8.13.0]]
.Beats MSI binaries do not support directories with a trailing slash
[%collapsible]
====

*Details*

Due to changes introduced to support customizing an MSI install folder (see link:https://github.com/elastic/elastic-stack-installers/pull/209[#209]), Beats MSI binaries, which currently are in beta, will not properly handle directories that end in a slash. This defect may affect many deployments using the {beats} MSI binaries.

*Impact* +

This issue has been link:https://github.com/elastic/elastic-stack-installers/pull/264[resolved] in version 8.14.0 and later releases. We recommend users of {beats} MSI to upgrade to 8.14 when that release becomes available.

====

[[known-issue-174855-8.13.0]]
.ECS fields are not included to the `index.query.default_field` in {agent} integrations
[%collapsible]
====
*Details*

Due to changes introduced to support the ecs@mappings component template (see link:https://github.com/elastic/kibana/pull/174855[elastic/kibana/pull/174855]), {fleet} no longer includes ECS fields in the integrations' `index.query.default_field`. Not including ECS fields in the `index.query.default_field` setting may affect integrations that rely on fieldless queries (when no field is specified for a query).

If you run a query without specifying a field, the query will not return results for ECS fields.

*Impact* +

In version 8.14.0 and later, {fleet} sets `index.query.default_field` to `*`, so agentless queries will work as expected. We recommend users of {fleet} upgrade to 8.14 when that release becomes available.

If you are running 8.13.x and unable to upgrade to 8.14.0, you can follow the workarounds described in the link:https://support.elastic.co/knowledge/bbdbeb57.
====

[discrete]
[[new-features-8.13.0]]
=== New features

The 8.13.0 release added the following new and notable features.

{fleet}::
* Adds support for the `subobjects` setting on the object type mapping ({kibana-pull}171826[#171826]).

{fleet-server}::
* Add support for storing output secrets in a new `secrets` block. {fleet-server-pull}3061[3061] {fleet-server-issue}2966[2966]
* Add support for the remote {es} output type in {fleet-server}. {fleet-server-pull}3051[3051]
* Report the health state of remote {es} outputs to the `logs-fleet_server.output_health-default` data stream. {fleet-server-pull}3127[3127] {fleet-server-issue}3116[3116]
* Add a `policy_debounce_time` configuration to add a forced delay to the policy index monitor when it successfully gathers new documents. {fleet-server-pull}3234[3234]

{agent}::
* Log a summary of each policy configuration change received from {fleet}. {agent-pull}4050[#4050] {agent-issue}3406[#3406]
* Add the full version number to the installation directory name. {agent-pull}4193[#4193] {agent-issue}2579[#2579]
* Ignore Kubernetes node and namespace update events that do not change pod metadata. {agent-pull}4226[#4226] {beats-issue}37338[#37338]
* Add the new ETW input mapping to the Filebeat specification so that it's available in {agent}. {agent-pull}4037[#4037] {beats-pull}36915[#36915]
* Add the new WebSocket input mapping to the Filebeat specification so that it's available in {agent}. {agent-pull}4242[#4242] {beats-pull}37774[#37774]
* Create the `.installed` marker earlier on in the install process, allowing the use of `elastic-agent uninstall` to cleanup if the install fails. {agent-pull}4172[#4172] {agent-issue}4051[#4051]
* Add a postrm script to {agent} DEB and RPM packages. {agent-pull}4334[#4334] {agent-issue}3784[#3784] {agent-issue}4267[#4267]
* Kubernetes secrets provider has been improved to update a Kubernetes secret  when the secret value changes. {agent-pull}4371[#4371] {agent-issue}4168[#4168]
* Upgrade link:https://github.com/elastic/elastic-agent-system-metrics[elastic-agent-system-metrics] to version 0.9.2. {agent-pull}4383[#4383]
* Allow users to configure number of output workers (for outputs that support workers) with either `worker` or `workers`. {beats-pull}38257[38257]

[discrete]
[[enhancements-8.13.0]]
=== Enhancements

{fleet}::
* Adds `skipRateLimitCheck` flag to the Upgrade API and Bulk_upgrade API ({kibana-pull}176923[#176923]).
* Adds making datastream rollover lazy ({kibana-pull}176565[#176565]).
* Stops creating  the `{type}-{datastet}@custom` component template during package installation ({kibana-pull}175469[#175469]).
* Adds the `xpack.fleet.isAirGapped` flag ({kibana-pull}174214[#174214]).
* Add a warning when downloading the new version in an agent upgrade is failing ({kibana-pull}173844[#173844]).
* Adds a message explaining why an agent is not upgradeable ({kibana-pull}173253[#173253]).
* Makes logs-* and metrics-* data views available across all spaces ({kibana-pull}172991[#172991]).
* Adds flag for pre-release to templates/inputs endpoint ({kibana-pull}174471[#174471]).
* Adds concurrency control to Fleet data stream API handler ({kibana-pull}174087[#174087]).
* Adds a handlebar helper to percent encode a given string ({kibana-pull}173119[#173119]).

{fleet-server}::
* Relax version checks in snapshot builds to support automated testing during minor release updates. {fleet-server-pull}3039[3039] {fleet-server-issue}2960[2960]
* Add top level keys for policy definition into {fleet-server} OpenAPI specification. {fleet-server-pull}3048[3048]
* Define the `action.data` and `ack` event schemas. {fleet-server-pull}3060[3060]
* Add additional transaction labels with {es} error details to requests. {fleet-server-pull}3124[3124] {fleet-server-issue}3098[3098]
* Calls with unauthorized API keys now return a `401` error. {fleet-server-pull}3135[3135] {fleet-server-issue}2861[2861]
* Use the Shutdown method with a timeout to gracefully halt HTTP servers. {fleet-server-pull}3165[3165] {fleet-server-issue}2902[2902]
* Replace the policy and action limiters with a unified checkin limiter. {fleet-server-pull}3255[3255] {fleet-server-issue}2254[3254]
* Change the response code for {es} call failures to `503`. {fleet-server-pull}3235[3235] {fleet-server-issue}2852[2852]

{agent}::
* Move the control socket path to always be inside of the top level of the {agent} installation directory. {agent-pull}3909[#3909] {agent-issue}3840[#3840]
* Add mTLS flags to {agent} install and enroll commands to enable use of certificates for communication in on-prem proxy setups. {agent-pull}4007[#4007]
* Improve error handling by adding error descriptors to the `inspect` command and config methods. {agent-pull}4074[#4074]
* Add an `agent.providers.initial_default` configuration flag to disable providers by default. {agent-pull}4166[#4166] {agent-issue}4145[#4145]
* Add environment variable bindings so that {fleet-server} and {agents} started in container mode can specify mTLS variables. {agent-pull}4261[#4261]

[discrete]
[[bug-fixes-8.13.0]]
=== Bug fixes

{fleet}::
* Fixes a bug where secret values were not deleted on output type change ({kibana-pull}178964[#178964]).
* Fixes formatting for some integrations on the overview page ({kibana-pull}178937[#178937]).
* Fixes the name of {es} output workers configuration key ({kibana-pull}178329[#178329]).
* Fixes clean up of the `.fleet-policies` entries when deleting an agent policy. ({kibana-pull}178276[#178276]).
* Fixes only showing remote {es} output health status if later than last updated time ({kibana-pull}177685[#177685]).
* Fixes status summary when `showUpgradeable` is selected ({kibana-pull}177618[#177618]).
* Fixes issue of agent sometimes not getting inputs using a new agent policy with system integration ({kibana-pull}177594[#177594]).
* Fixes the activity flyout keeping the scroll state on rerender ({kibana-pull}177029[#177029]).
* Fixes inactive popover tour not resetting ({kibana-pull}176929[#176929]).
* Fixes `isPackageVersionOrLaterInstalled` to check for installed package ({kibana-pull}176532[#176532]).
* Removes pre-release exception for Synthetics package ({kibana-pull}176249[#176249]).
* Fixes output validation when creating package policy ({kibana-pull}175985[#175985]).
* Fixes allowing an agent to upgrade to a newer patch version than fleet-server ({kibana-pull}175775[#175775]).
* Fixes asset creation during custom integration installation ({kibana-pull}174869[#174869]).
* Fixes cascading agent policy's namespace to package policies ({kibana-pull}174776[#174776]).

{fleet-server}::
* Add missing `Elastic-Api-Version` and `X-Request-Id` headers to the {fleet-server} OpenAPI specification. {fleet-server-pull}3044[3044]
* Replace all secret references in input objects. {fleet-server-pull}3086[3086] {fleet-server-issue}3083[3083]
* Deprecate the redundant `fleet.agent.logging.level` attribute. {fleet-server-pull}3195[3195] {fleet-server-issue}3126[3126]
* Add validation to make sure that status and message are present in the checkin API request body.  {fleet-server-pull}3233[3233] {fleet-server-issue}2420[2420]
* Fix a bug where agents were stuck in non-upgradeable state after an upgrade. {fleet-server-pull}3264[3264] {fleet-server-issue}3263[3263]
* Fix chunked file delivery so that files are delivered in order. {fleet-server-pull}3283[#3283]
* Fix a bug where the self monitor stops output health reporting if the output configuration is not acknowledged by agents. {fleet-server-pull}3335[#3335] {fleet-server-issue}3334[3334]

{agent}::
* Fix component control protocol to allow checkin to be chunked across multiple messages. Fixes errors related to the gRPC max message size being exceeded. {agent-pull}3884[#3884] {agent-issue}2460[#2460]
* Fix the creation of directories when unpacking tar.gz packages. {agent-pull}4100[#4100] {agent-issue}4093[#4093]
* Set a timeout of 1 minute for the FQDN lookup function. {agent-pull}4147[#4147]
* Increase timeout for file removal during {agent} uninstall. {agent-pull}4310[#4310] {agent-issue}4164[#4164]

// end 8.13.0 relnotes

// ---------------------
//TEMPLATE
//Use the following text as a template. Remember to replace the version info.

// begin 8.7.x relnotes

//[[release-notes-8.7.x]]
//== {fleet} and {agent} 8.7.x

//Review important information about the {fleet} and {agent} 8.7.x release.

//[discrete]
//[[security-updates-8.7.x]]
//=== Security updates

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[breaking-changes-8.7.x]]
//=== Breaking changes

//Breaking changes can prevent your application from optimal operation and
//performance. Before you upgrade, review the breaking changes, then mitigate the
//impact to your application.

//[discrete]
//[[breaking-PR#]]
//.Short description
//[%collapsible]
//====
//*Details* +
//<Describe new behavior.> For more information, refer to {kibana-pull}PR[#PR].

//*Impact* +
//<Describe how users should mitigate the change.> For more information, refer to {fleet-guide}/fleet-server.html[Fleet Server].
//====

//[discrete]
//[[notable-changes-8.13.0]]
//=== Notable changes

//The following are notable, non-breaking updates to be aware of:

//* Changes to features that are in Technical Preview.
//* Changes to log formats.
//* Changes to non-public APIs.
//* Behaviour changes that repair critical bugs.

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[known-issues-8.7.x]]
//=== Known issues

//[[known-issue-issue#]]
//.Short description
//[%collapsible]
//====

//*Details*

//<Describe known issue.>

//*Impact* +

//<Describe impact or workaround.>

//====

//[discrete]
//[[deprecations-8.7.x]]
//=== Deprecations

//The following functionality is deprecated in 8.7.x, and will be removed in
//8.7.x. Deprecated functionality does not have an immediate impact on your
//application, but we strongly recommend you make the necessary updates after you
//upgrade to 8.7.x.

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[new-features-8.7.x]]
//=== New features

//The 8.7.x release Added the following new and notable features.

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[enhancements-8.7.x]]
//=== Enhancements

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[bug-fixes-8.7.x]]
//=== Bug fixes

//{fleet}::
//* add info

//{agent}::
//* add info

// end 8.7.x relnotes
