// Use these for links to issue and pulls.
:kibana-issue: https://github.com/elastic/kibana/issues/
:kibana-pull: https://github.com/elastic/kibana/pull/
:beats-issue: https://github.com/elastic/beats/issues/
:beats-pull: https://github.com/elastic/beats/pull/
:agent-libs-pull: https://github.com/elastic/elastic-agent-libs/pull/
:agent-issue: https://github.com/elastic/elastic-agent/issues/
:agent-pull: https://github.com/elastic/elastic-agent/pull/
:fleet-server-issue: https://github.com/elastic/fleet-server/issues/
:fleet-server-pull: https://github.com/elastic/fleet-server/pull/

[[release-notes]]
= Release notes

This section summarizes the changes in each release.

* <<release-notes-8.11.2>>
* <<release-notes-8.11.1>>
* <<release-notes-8.11.0>>

Also see:

* {kibana-ref}/release-notes.html[{kib} release notes]
* {beats-ref}/release-notes.html[{beats} release notes]


// begin 8.11.2 relnotes

[[release-notes-8.11.2]]
== {fleet} and {agent} 8.11.2

Review important information about {fleet-server} and {agent} for the 8.11.1 release.

IMPORTANT: The memory leak <<known-issue-115-8.11.1,known issue>> that affects Windows users running {agent} is resolved in this release. If you're currently on {agent} version 8.11.0 or 8.11.1, we recommend upgrading to 8.11.2 to avoid the issue. If you're on an earlier version, avoid upgrading to version 8.11.0 or 8.11.1 and update directly to version 8.11.2.

[discrete]
[[enhancements-8.11.2]]
=== Enhancements

{fleet}::
* Improve UX for policy secrets. {kibana-pull}171405[#171405]

{agent}::
* Add configuration parameters for the Kubernetes `leader_election` provider. {agent-pull}3625[#3625]
* Update NodeJS version bundled with Heartbeat to v18.18.2. {agent-pull}3655[#3655]
* Update Go version to 1.20.11. {agent-pull}3748[#3748]

[discrete]
[[bug-fixes-8.11.2]]
=== Bug fixes

{fleet}::
* Support integration secrets in a local package registry with variables `secret: true` and `required: false`. {kibana-pull}172078[#172078]
* Fix agent metrics retrieval on the agent list page, previously displaying N/A for metrics for users with more than 10 agents. {kibana-pull}172016[#172016]
* Only add `time_series_metric` if TSDB is enabled. {kibana-pull}171712[#171712]
* Fix inability to upgrade agents from version 8.10.4 to version 8.11. {kibana-pull}170974[#170974]

{agent}::
* Fix logging calls that have missing arguments. {agent-pull}3679[#3679]
* Fix {fleet}-managed {agent} ignoring the `agent.download.proxy_url` setting after a policy is updated. {agent-pull}3803[#3803] {agent-issue}3560[#3560]
* Create a custom `MarshalYAML()` method to properly handle error fields in agent diagnostics. {agent-pull}3835[#3835] {agent-issue}2940[#2940]

// end 8.11.2 relnotes

// begin 8.11.1 relnotes

[[release-notes-8.11.1]]
== {fleet} and {agent} 8.11.1

Review important information about {fleet-server} and {agent} for the 8.11.1 release.

IMPORTANT: Due to a memory leak issue, Windows users running {agent} are recommended to avoid upgrading to this release and waiting for the upcoming 8.11.2 release in which the issue is resolved. If you've already upgraded to version 8.11.0 or 8.11.1, we recommend upgrading to 8.11.2 as soon as it becomes available. See the <<known-issue-115-8.11.1,known issue>> for more detail.

[discrete]
[[breaking-changes-8.11.1]]
=== Breaking changes

[[breaking-3712-8.11.1]]
* The <<breaking-3712,breaking change>> that could prevent the {agent} or Integrations Server component from booting up within an ECE deployment has been resolved in this release.

[discrete]
[[known-issues-8.11.1]]
=== Known issues

[[known-issue-115-8.11.1]]
.Memory leak running {agent} in Windows environments with the System Integration
[%collapsible]
====

*Details*

A memory leak has been identified in {metricbeat} on Windows. The leak also affects the {agent} System integration which is implemented with {metricbeat}. The leak will eventually exhaust all memory on the host system, typically after several days.

*Impact* +

This issue has been fixed in upcoming version 8.11.2. For a Windows environment, we recommend waiting for the official release of 8.11.2 before upgrading from 8.10.x or earlier.

If you're already running {agent} version 8.11.0 or 8.11.1 on Windows, we recommend disabling the `process` and `process_summary` metrics in your System integration and restarting {agent}. Note that disablling these datasets will prevent the collection of process-related metrics.

Another workaround is to downgrade {agent} to a version below 8.11.0. Note that this could result in missing or reindexed logs or metrics as the "state" will not be persisted after {agent} is uninstalled and reinstalled.

====

[[known-issue-169825-8.11.1]]
.Current stack version is not in the list of {agent} versions in {kib} {fleet} UI
[%collapsible]
====

*Details*

On the {fleet} UI in {kib}:

* When adding a new {agent}, the user interface shows a previous version instead of the current version.
* When attempting to upgrade, the modal window to pick the version shows an earlier version as the latest version.

*Impact* +

You can use the following steps as a workaround:

*When upgrading {agent} currently on versions 8.10.3 or lower (simpler)*

. Open the {fleet} UI. Under the *Agents* tab select *Upgrade agent* from the actions menu. The version field in the *Upgrade agent* UI allows you to enter any version.
. Enter `8.11.0` or whichever version you want to upgrade the [agents] to. Do not choose a version above the version of {kib} or {fleet-server} that you're running.

*When upgrading {agent} currently on any version (more complex, requires API)*

. Open {kib} and navigate to *Management -> Dev Tools*.
. Choose one of the API requests below and submit it through the console. Each of the requests uses version `8.11.0` as an example, but this can be changed to any available version.
+
* To upgrade a single {agent} to any version, run:
+
[source,console]
----
POST kbn:/api/fleet/agents/<Elastic Agent ID>/upgrade
{"version":"8.11.0"}
----
+
* To upgrade a set of {agents} based on a known set of agent IDs, run:
+
[source,console]
----
POST kbn:/api/fleet/agents/bulk_upgrade
{
  "version":"8.11.0",
  "agents":["<Elastic Agent ID>","<Another Elastic Agent ID>"],
  "start_time":"2023-11-10T09:41:39.850Z"
}
----
* To upgrade a set of {agents} running a specific policy, and below a specific version (for example, `8.11.0`), run:
+
[source,console]
----
POST kbn:/api/fleet/agents/bulk_upgrade
{
  "agents": "fleet-agents.policy_id:<Elastic Fleet Policy ID> and fleet-agents.agent.version<<VERSION>",
  "version": "8.11.0"
}
----
+
[source,console]
----
POST kbn:/api/fleet/agents/bulk_upgrade
{
  "agents": "fleet-agents.policy_id:uuid1-uuid2-uuid3-uuid4 and fleet-agents.agent.version<8.11.0",
  "version": "8.11.0"
}
----

TIP: To find the ID for any {agent}, open the **Agents** tab in {fleet} and select **View agent** from the **Actions** menu. The agent ID and other details are shown.

To learn more about these requests, refer to the <<fleet-api-docs,{fleet} API documentation>>.

====

[discrete]
[[new-features-8.11.1]]
=== New features

The 8.11.1 release Added the following new and notable features.

{agent}::
* Add the dimensions `component.id` and `component.binary` to {agent} and {beats} monitoring output, to support unique entries for the Time Series Database (TSDB) feature. {agent-pull}3626[#3626] https://github.com/elastic/integrations/issues//7977[#7977]

[discrete]
[[bug-fixes-8.11.1]]
=== Bug fixes

{fleet}::
* Append space ID to security solution tag. ({kibana-pull}170789[#170789]).
* Modify bulk unenroll to include inactive agents. ({kibana-pull}170249[#170249]).

// end 8.11.1 relnotes

// begin 8.11.0 relnotes

[[release-notes-8.11.0]]
== {fleet} and {agent} 8.11.0

Review important information about {fleet-server} and {agent} for the 8.11.0 release.

IMPORTANT: Due to a memory leak issue, Windows users running {agent} are recommended to avoid upgrading to this release and waiting for the upcoming 8.11.2 release in which the issue is resolved. If you've already upgraded to 8.11.0 or 8.11.1, we recommend upgrading to 8.11.2 as soon as it becomes available. See the <<known-issue-115-8.11.0,known issue>> for more detail.

[discrete]
[[security-updates-8.7.x]]
=== Security updates

{agent}::
* Updated Go version to 1.20.10. {agent-pull}3[#3601]

[discrete]
[[breaking-changes-8.11.0]]
=== Breaking changes

Breaking changes can prevent your application from optimal operation and
performance. Before you upgrade, review the breaking changes, then mitigate the
impact to your application.

[discrete]
[[breaking-3712]]
.Integrations Server / APM unable to boot in specific ECE environments
[%collapsible]
====
*Details* +
A permissions change in the {agent} Docker container can prevent the {agent} or Integrations Server component from booting up within an ECE deployment. The change affects ECE installations that are deployed with a Linux UID other than `1000`.

*Impact* +
ECE users with deployments that include APM or Integrations Server are recommended to wait for the next patch release, which is planned to include a fix for this problem.
====

[discrete]
[[breaking-3505]]
.Compression is enabled by default for {agent} {es} outputs
[%collapsible]
====
*Details* +
The default compression level for {es} outputs is changing from `0` to `1`. 

*Impact* +
On typical workloads this is expected to decrease network data volume by 70-80%, while increasing CPU use by 20-25% and ingestion time by 10%. The previous behavior can be restored by adding the setting `compression_level: 0` to the agent output configuration.
====

[discrete]
[[breaking-3593]]
.`elastic-agent-autodiscover` library has been updated to version 0.6.4, disabling metadata For `kubernetes.deployment` and `kubernetes.cronjob` fields.
[%collapsible]
====
*Details* +
The `elastic-agent-autodiscover` Kubernetes library by default comes with `add_resource_metadata.deployment=false` and `add_resource_metadata.cronjob=false`.

*Impact* +
Pods that will be created from deployments or cronjobs will not have the extra metadata field for `kubernetes.deployment` or `kubernetes.cronjob`, respectively. This change was made to avoid the memory impact of keeping the feature enabled in big Kubernetes clusters.
For more information, refer to {agent-pull}3593[#3593].
====

[discrete]
[[known-issues-8.11.0]]
=== Known issues

[[known-issue-115-8.11.0]]
.Memory leak running {agent} in Windows environments with the System Integration
[%collapsible]
====

*Details*

A memory leak has been identified in {metricbeat} on Windows. The leak also affects the {agent} system integration which is implemented with {metricbeat}. The leak will eventually exhaust all memory on the host system, typically after several days.

*Impact* +

This issue has been fixed in upcoming version 8.11.2. For a Windows environment, we recommend waiting for the official release of 8.11.2 before upgrading from 8.10.x or earlier.

If you're already running {agent} version 8.11.0 or 8.11.1 on Windows, we recommend disabling the `process` and `process_summary` metrics in your System integration and restarting {agent}. Note that disablling these datasets will prevent the collection of process-related metrics.

Another workaround is to downgrade {agent} to a version below 8.11.0. Note that this could result in missing or reindexed logs or metrics as the "state" will not be persisted after {agent} is uninstalled and reinstalled.

====

[[known-issue-169825-8.11.0]]
.Current stack version is not in the list of {agent} versions in {kib} {fleet} UI
[%collapsible]
====

*Details*

On the {fleet} UI in {kib}:

* When adding a new {agent}, the user interface shows a previous version instead of the current version.
* When attempting to upgrade, the modal window to pick the version shows an earlier version as the latest version.

*Impact* +

You can use the following steps as a workaround:

*When upgrading {agent} currently on versions 8.10.3 or lower (simpler)*

. Open the {fleet} UI. Under the *Agents* tab select *Upgrade agent* from the actions menu. The version field in the *Upgrade agent* UI allows you to enter any version.
. Enter `8.11.0` or whichever version you want to upgrade the [agents] to. Do not choose a version above the version of {kib} or {fleet-server} that you're running.

*When upgrading {agent} currently on any version (more complex, requires API)*

. Open {kib} and navigate to *Management -> Dev Tools*.
. Choose one of the API requests below and submit it through the console. Each of the requests uses version `8.11.0` as an example, but this can be changed to any available version.
+
* To upgrade a single {agent} to any version, run:
+
[source,console]
----
POST kbn:/api/fleet/agents/<Elastic Agent ID>/upgrade
{"version":"8.11.0"}
----
+
* To upgrade a set of {agents} based on a known set of agent IDs, run:
+
[source,console]
----
POST kbn:/api/fleet/agents/bulk_upgrade
{
  "version":"8.11.0",
  "agents":["<Elastic Agent ID>","<Another Elastic Agent ID>"],
  "start_time":"2023-11-10T09:41:39.850Z"
}
----
* To upgrade a set of {agents} running a specific policy, and below a specific version (for example, `8.11.0`), run:
+
[source,console]
----
POST kbn:/api/fleet/agents/bulk_upgrade
{
  "agents": "fleet-agents.policy_id:<Elastic Fleet Policy ID> and fleet-agents.agent.version<<VERSION>",
  "version": "8.11.0"
}
----
+
[source,console]
----
POST kbn:/api/fleet/agents/bulk_upgrade
{
  "agents": "fleet-agents.policy_id:uuid1-uuid2-uuid3-uuid4 and fleet-agents.agent.version<8.11.0",
  "version": "8.11.0"
}
----

TIP: To find the ID for any {agent}, open the **Agents** tab in {fleet} and select **View agent** from the **Actions** menu. The agent ID and other details are shown.

To learn more about these requests, refer to the <<fleet-api-docs,{fleet} API documentation>>.

====


[discrete]
[[new-features-8.11.0]]
=== New features

The 8.11.0 release Added the following new and notable features.

{fleet}::
* Set env variable `ELASTIC_NETINFO:false` in {kib} ({kibana-pull}166156[#166156]).
* Added restart upgrade action ({kibana-pull}166154[#166154]).
* Adds ability to set a proxy for agent binary source ({kibana-pull}164168[#164168]).
* Adds ability to set a proxy for agent download source ({kibana-pull}164078[#164078]).

{agent}::
* Add support for processors in hints-based Kubernetes autodiscover. {agent-pull}3107[#3107] {agent-issue}2959[#2959]
* Print out {agent} installation steps to show progress. {agent-pull}3338[#3338]
* Add colors to {agent} messages printed by the elastic-agent logs command based on their level. {agent-pull}3345[#3345]

[discrete]
[[enhancements-8.11.0]]
=== Enhancements

{fleet}::
* Adds sidebar navigation showing headings extracted from the readme ({kibana-pull}167216[#167216]).

{fleet-server}::
* Expand APM traces to track coordinator and monitor transactions. Add additonal spans across all API endpoints to better track what the server does. Add spans to bulker interactions that link with the queue flush transaction that the bulk action is executed through. {fleet-server-pull}2929[#2929]
* Add endpoint to serve PGP keys that clients can use when validating upgrades in cases where the embedded PGP key in a client is compromised and the client can't reach the internet. {fleet-server-pull}2977[#2977] {fleet-server-issue}2887[#2887]
* Add ActionLimit and a Gzip writer pool to handle checkin responses, to help prevent OOM errors when updates are issued to many clients. {fleet-server-pull}2929[#2994]
* Send errors in API calls and bulker flushes to APM. fleet-server-pull}3053[#3053]

{agent}::
* Improve {agent} uninstall on Windows by adding delay between retries when file removal is blocked by busy files. {agent-pull}3431[#3431] {agent-issue}3221[#3221]
* Support the NETINFO variable in Elastic Kubernetes manifests. Setting a new environmental variable `ELASTIC_NETINFO=false` globally disables the `netinfo.enabled` parameter of the `add_host_metadata` processor. This disables the indexing of `host.ip` and `host.mac` fields. {agent-pull}3354[#3354]
* The {agent} uninstall process now finds and kills any running upgrade Watcher process. Uninstalls initiated within 10 minutes of a previous upgrade now work as expected. {agent-pull}3384[#3384] {agent-issue}3371[#3371]
* Fix the Kubernetes `deploy/kubernetes/creator_k8.sh` script to correcly exclude configmaps. {agent-pull}3396[#3396]
* Allow fetching the GPG key used for upgrade package signature verification from {fleet-server}. This enables upgrades using rotated GPG keys in air gapped environments where {fleet-server} is the only reachable URI. {agent-pull}3543[#3543] {agent-issue}3264[#3264]
* Enable tamper protection feature flag by default for {agent} version 8.11.0. {agent-pull}3478[#3478]
* Increase {agent} monitoring metrics interval from 10s to 60s to reduce the default ingestion load and long term storage requirements. {agent-pull}3578[#3578]

[discrete]
[[bug-fixes-8.11.0]]
=== Bug fixes

{fleet}::
* Vastly improve performance of Fleet final pipeline's date formatting logic for `event.ingested` ({kibana-pull}167318[#167318]).

{fleet-server}::
* Fix errors produced by the {fleet-server} bulker to be ECS compliant. {fleet-server-pull}3034[#3034] {fleet-server-issue}3033[#3033]

{agent}::
* Enable resilient handling of air gapped PGP checks. {agent} should not fail when remote PGP is specified (or official Elastic fallback PGP is used) and remote is not available. {agent-pull}3427[#3427] {agent-pull}3426[#3426] {agent-issue}3368[#3368]
* Prevent a standalone {agent} from being upgraded if an upgrade is already in progress. {agent-pull}3473[#3473] {agent-issue}2706[#2706]
* Fix a bug that affected reporting progress of the {agent} artifact download during an upgrade. {agent-pull}3548[#3548]
* Upgrade `elastic-agent-libs` to v0.6.0 to fix the {agent} Windows service becoming unresponsive. Fixes Windows service timeouts during WMI queries and during service shutdown. {agent-pull}3632[#3632] {agent-issue}3061[#3061]
* Increase wait period between service restarts on failure to 15s on Windows. {agent-pull}3657[#3657]
* Prevent multiple attempts by {agent} to stop an already stopped service. {agent-pull}3482[#3482]

// end 8.11.0 relnotes


// ---------------------
//TEMPLATE
//Use the following text as a template. Remember to replace the version info.

// begin 8.7.x relnotes

//[[release-notes-8.7.x]]
//== {fleet} and {agent} 8.7.x

//Review important information about the {fleet} and {agent} 8.7.x release.

//[discrete]
//[[security-updates-8.7.x]]
//=== Security updates

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[breaking-changes-8.7.x]]
//=== Breaking changes

//Breaking changes can prevent your application from optimal operation and
//performance. Before you upgrade, review the breaking changes, then mitigate the
//impact to your application.

//[discrete]
//[[breaking-PR#]]
//.Short description
//[%collapsible]
//====
//*Details* +
//<Describe new behavior.> For more information, refer to {kibana-pull}PR[#PR].

//*Impact* +
//<Describe how users should mitigate the change.> For more information, refer to {fleet-guide}/fleet-server.html[Fleet Server].
//====

//[discrete]
//[[known-issues-8.7.x]]
//=== Known issues

//[[known-issue-issue#]]
//.Short description
//[%collapsible]
//====

//*Details*

//<Describe known issue.>

//*Impact* +

//<Describe impact or workaround.>

//====

//[discrete]
//[[deprecations-8.7.x]]
//=== Deprecations

//The following functionality is deprecated in 8.7.x, and will be removed in
//8.7.x. Deprecated functionality does not have an immediate impact on your
//application, but we strongly recommend you make the necessary updates after you
//upgrade to 8.7.x.

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[new-features-8.7.x]]
//=== New features

//The 8.7.x release Added the following new and notable features.

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[enhancements-8.7.x]]
//=== Enhancements

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[bug-fixes-8.7.x]]
//=== Bug fixes

//{fleet}::
//* add info

//{agent}::
//* add info

// end 8.7.x relnotes
