// Use these for links to issue and pulls.
:kibana-issue: https://github.com/elastic/kibana/issues/
:kibana-pull: https://github.com/elastic/kibana/pull/
:beats-issue: https://github.com/elastic/beats/issues/
:beats-pull: https://github.com/elastic/beats/pull/
:agent-libs-pull: https://github.com/elastic/elastic-agent-libs/pull/
:agent-issue: https://github.com/elastic/elastic-agent/issues/
:agent-pull: https://github.com/elastic/elastic-agent/pull/
:fleet-server-issue: https://github.com/elastic/fleet-server/issues/
:fleet-server-pull: https://github.com/elastic/fleet-server/pull/

[[release-notes]]
= Release notes

This section summarizes the changes in each release.

* <<release-notes-8.17.4>>
* <<release-notes-8.17.3>>
* <<release-notes-8.17.2>>
* <<release-notes-8.17.1>>
* <<release-notes-8.17.0>>

Also see:

* {kibana-ref}/release-notes.html[{kib} release notes]
* {beats-ref}/release-notes.html[{beats} release notes]



// begin 8.17.4 relnotes

[[release-notes-8.17.4]]
== {fleet} and {agent} 8.17.4

Review important information about the  8.17.4 release.

[discrete]
[[new-features-8.17.4]]
=== New features

The 8.17.4 release adds the following new and notable features.

{agent}::
* Add managed OTLP endpoint sample configurations. {agent-pull}6630[#6630] 

[discrete]
[[enhancements-8.17.4]]
=== Enhancements

{agent}::
* Improve `kubernetes_secrets` provider secret logging. {agent-pull}6841[#6841] {agent-issue}6187[#6187]
* Include all metadata that is sent to {fleet} in the `agent-info.yaml` file in diagnostics by default. {agent-pull}7029[#7029] 
* Add API key prefix to motel host configurations. {agent-pull}7063[#7063] 

[discrete]
[[bug-fixes-8.17.4]]
=== Bug fixes

{agent}::
* Add conditions to `copy_fields` processors to prevent spamming the debug logs. {agent-pull}6730[#6730] {agent-issue}5299[#5299]
* Improve message when audit or uninstall returns 401. {agent-pull}6735[#6735] {agent-issue}6711[#6711]
* Fix `secret_paths` redaction along complex paths. {agent-pull}6710[#6710] 
* Make enroll command backoff more conservative. {agent-pull}6983[#6983] {agent-issue}6761[#6761]
* Fix an issue where `fixpermissions` on Windows incorrectly returned an error message due to improper handling of Windows API return values. {agent-pull}7059[#7059] {agent-issue}6917[#6917]
* Support IPv6 hosts in enroll URL. {agent-pull}7036[#7036] 
* Support IPv6 hosts in GRPC configuration. {agent-pull}7035[#7035] 
* Rotate logger output file when writing to a symbolic link. {agent-pull}6938[#6938] 
* Do not fail Windows permission updates on missing files or paths. {agent-pull}7305[#7305] {agent-issue}7301[#7301]
* Make `otelcol` executable in the Docker image. {agent-pull}7345[#7345] 
* Fix {es} exporter configuration in `kube-stack` values. {agent-pull}7380[#7380] 

// end 8.17.4 relnotes

// begin 8.17.3 relnotes

[[release-notes-8.17.3]]
== {fleet} and {agent} 8.17.3

Review important information about the {fleet} and {agent} 8.17.3 release.

[discrete]
[[enhancements-8.17.3]]
=== Enhancements

{agent}::
* Add the configuration files for the Elastic Distribution of OTel Collector that will be provided during the {kib} OpenTelemetry Host and Kubernetes onboarding flow for MOTel. {agent-pull}6641[#6630]

[discrete]
[[bug-fixes-8.17.3]]
=== Bug fixes

{agent}::
* Add missing checks for null values in AST collection nodes. {agent-pull}7009[#7009] {agent-issue}6999[#6999]
* Set the gateway Kubernetes `spec.replicas` for the gateway OpenTelemetry Collector to prevent horizontal Pod autoscaler fails. {agent-pull}7011[#7011]

// end 8.17.3 relnotes

// begin 8.17.2 relnotes

[[release-notes-8.17.2]]
== {fleet} and {agent} 8.17.2

Review important information about the {fleet} and {agent} 8.17.2 release.

[discrete]
[[security-updates-8.17.2]]
=== Security updates

{fleet-server}::
* Upgrade `golang.org/x/net` to v0.34.0 and `golang.org/x/crypto` to v0.32.0. {fleet-server-pull}4405[#4405]


[discrete]
[[enhancements-8.17.2]]
=== Enhancements

{agent}::
* Upgrade NodeJS for Heartbeat to LTS v18.20.6. {agent-pull}6641[#6641]

[discrete]
[[bug-fixes-8.17.2]]
=== Bug fixes

{agent}::
* Emit variables even if provider data is empty from the start. {agent-pull}6598[#6598]

// end 8.17.2 relnotes

// begin 8.17.1 relnotes

[[release-notes-8.17.1]]
== {fleet} and {agent} 8.17.1

Review important information about the {fleet} and {agent} 8.17.1 release.

[discrete]
[[breaking-changes-8.17.1]]
=== Breaking changes

Breaking changes can prevent your application from optimal operation and
performance. Before you upgrade, review the breaking changes, then mitigate the
impact to your application.

{agent}::
* {agent} Docker images for {ecloud} have been reverted from having been based off of Ubuntu 24.04 to being based off of Ubuntu 20.04. This is to ensure compatibility with {ece}, support for new Wolfi-based images, and for GNU C Library (glibc) compatibility. {agent-pull}6393[#6393]

[discrete]
[[known-issues-8.17.1]]
=== Known issues

[[known-issue-1671]]
.{kib} out of memory crashes on 1 GB {ecloud} {kib} instances using {elastic-sec} view
[%collapsible]
====

*Details*

{ecloud} deployments that use the smallest available {kib} instance size of 1 GB may crash due to out of memory errors when the Security UI is loaded. 

*Impact* +

The root cause is inefficient memory allocation, and this is exacerbated when the prebuilt security rules package is installed on the initial load of the {elastic-sec} UI.

As a workaround, you can upgrade your deployment to 8.17.1 in which this issue has been resolved by https://github.com/elastic/kibana/pull/208869[#208869] and https://github.com/elastic/kibana/pull/208475[#208475].

====

[discrete]
[[new-features-8.17.1]]
=== New features

The 8.17.1 release added the following new and notable features.

{agent}::
* Add the link:https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/loadbalancingexporter[Otel loadbalancing exporter] to {agent}. {agent-pull}6315[#6315]

[discrete]
[[enhancements-8.17.1]]
=== Enhancements

{agent}::

* Respond with an error message in case the user running the `enroll` command and the user who is the owner of the {agent} program files don't match. {agent-pull}6144[#6144] {agent-issue}4889[#4889]
* Implement the `MarshalJSON` method on the `component.Component` struct, so that when the component model is logged, the output does not contain any secrets that might be part of the component model. {agent-pull}6329[#6329] {agent-issue}5675[#5675]

[discrete]
[[bug-fixes-8.17.1]]
=== Bug fixes

{fleet-server}::
* Do not set the `unenrolled_at` attribute when the audit/unenroll API is called. {fleet-server-pull}4221[#4221] {agent-issue}6213[#6213]
* Remove PGP endpoint auth requirement so that air-gapped {agents} can retreive a PGP key from {fleet-server}. {fleet-server-pull}4256[#4256] {fleet-server-issue}4255[#4255]

{agent}::
* During uninstall, call the audit or unenroll API before components are stopped, if {agent} is running a {fleet-server} instance. {agent-pull}6085[#6085] {agent-issue}5752[#5752]
* Update OTel components to v0.115.0. {agent-pull}6391[#6391]
* Restore the `cloud-defend` binary which was accidentally removed in version 8.17.0. {agent-pull}6470[#6470] {agent-issue}6469[#6469]

// end 8.17.1 relnotes

// begin 8.17.0 relnotes

[[release-notes-8.17.0]]
== {fleet} and {agent} 8.17.0

Review important information about the {fleet} and {agent} 8.17.0 release.

[discrete]
[[breaking-changes-8.17.0]]
=== Breaking changes

Breaking changes can prevent your application from optimal operation and
performance. Before you upgrade, review the breaking changes, then mitigate the
impact to your application.

{agent}::
* {agent} is now compiled using Debian 11 and linked against glibc 2.31 instead of 2.19. Drops support for Debian 10. {agent-pull}5847[#5847]

[discrete]
[[known-issues-8.17.0]]
=== Known Issues

[discrete]
[[known-issue-6213-8-17-0]]
.An {agent} with the Defend integration may report an Orphaned status and will not be able to be issued an upgrade action through {fleet}.
[%collapsible]
====
*Details* +
A known issue in the {agent} may prevent it from being targetted with an upgrade action for a future release.
This may occur if the Defend integration is used and the agent is stopped on a running instance for too long.
An agent may be stopped as part of an upgrade process.

*Impact* +
A bug fix is present in the 8.17.1 release of {fleet} that will prevent this from occuring.

If you have agents that are affected, the workaround is as follows:
[source,shell]
----
# Get a Token to issue an update_by_query request:
curl -XPOST --user elastic:${SUPERUSER_PASS} -H 'x-elastic-product-origin:fleet' -H'content-type:application/json' "https://${ELASTICSEARCH_HOST}/_security/service/elastic/fleet-server/credential/token/fix-unenrolled"

# Issue an update_by_query request that targets effected agents:
curl -XPOST -H 'Authorization: Bearer ${TOKEN}' -H 'x-elastic-product-origin:fleet' -H 'content-type:application/json' "https://${ELASTICSEARCH_HOST}/.fleet-agents/_update_by_query" -d '{"query": {"bool": {"must": [{ "exists": { "field": "unenrolled_at" } }],"must_not": [{ "term": { "active": "false" } }]}},"script": {"source": "ctx._source.unenrolled_at = null;","lang": "painless"}}'
----
====

[discrete]
[[new-features-8.17.0]]
=== New features

The 8.17.0 release Added the following new and notable features.

{fleet}::
* Expose advanced file logging configuration in the UI. {kibana-pull}200274[#200274]

{agent}::
* Add support for running as a pre-existing user when installing in unprivileged mode, with technical preview support for pre-existing Windows Active Directory users. {agent-pull}5988[#5988] {agent-issue}4585[#4585]
* Add a new custom link:https://github.com/elastic/integrations/tree/main/packages/filestream[Filestream logs integration]. This will enable migration from the custom log integration which is based on a log input that is planned for deprecation. https://github.com/elastic/integrations/pull/11332[#11332].

[discrete]
[[enhancements-8.17.0]]
=== Enhancements

{fleet}::
* Filter the integrations/packages list shown in the UI depending on the `policy_templates_behavior` field. {kibana-pull}200605[#200605]
* Add a `<type>@custom` component template to integrations index template's `composed_of` array. {kibana-pull}192731[#192731]

{fleet-server}::
* Update `elastic-agent-libs` to version `0.14.0`. {fleet-server-pull}4042[#4042]

{agent}::
* Enable persistence in the configuration provided with our OTel Collector distribution. {agent-pull}5549[#5549]
* Restrict using the CLI to upgrade for {fleet}-managed {agents}. {agent-pull}5864[#5864] {agent-issue}4890[#4890]
* Add `os_family`, `os_platform` and `os_version` to the {agent} host provider, enabling differentiating Linux distributions. This is required to support Debian 12 and other distributions that are moving away from traditional log files in favour of Journald. {agent-pull}5941[#5941] https://github.com/elastic/integrations/issues/10797[10797] https://github.com/elastic/integrations/pull/11618[11618]
* Emit Pod data only for Pods that are running in the Kubernetes provider. {agent-pull}6011[#6011] {agent-issue}5835[#5835] {agent-issue}5991[#5991]
* Remove {endpoint-sec} from Linux container images. {endpoint-sec} cannot run in containers since it has a systemd dependency. {agent-pull}6016[#6016] {agent-issue}5495[#5495]
* Update OTel components to v0.114.0. {agent-pull}6113[#6113]
* Redact common secrets like API keys and passwords in the output from `elastic-agent inspect` command. {agent-pull}6224[#6224]

[discrete]
[[bug-fixes-8.17.0]]
=== Bug fixes

{fleet}::
* Allow creation of an integration policy with no agent policies. {kibana-pull}201051[#201051]

{fleet-server}::
* Fix `server.address` field which was appearing empty in HTTP request logs. {fleet-server-pull}4142[#4142]
* Remove a race condition that may occur when remote ES outputs are used. {fleet-server-pull}4171[#4171] {fleet-server-pull}4170[#4170]

{agent}::
* Make redaction of common keys in diagnostics case insensitive. {agent-pull}6109[#6109]


// end 8.17.0 relnotes

// ---------------------
//TEMPLATE
//Use the following text as a template. Remember to replace the version info.

// begin 8.7.x relnotes

//[[release-notes-8.7.x]]
//== {fleet} and {agent} 8.7.x

//Review important information about the {fleet} and {agent} 8.7.x release.

//[discrete]
//[[security-updates-8.7.x]]
//=== Security updates

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[breaking-changes-8.7.x]]
//=== Breaking changes

//Breaking changes can prevent your application from optimal operation and
//performance. Before you upgrade, review the breaking changes, then mitigate the
//impact to your application.

//[discrete]
//[[breaking-PR#]]
//.Short description
//[%collapsible]
//====
//*Details* +
//<Describe new behavior.> For more information, refer to {kibana-pull}PR[#PR].

//*Impact* +
//<Describe how users should mitigate the change.> For more information, refer to {fleet-guide}/fleet-server.html[Fleet Server].
//====

//[discrete]
//[[notable-changes-8.13.0]]
//=== Notable changes

//The following are notable, non-breaking updates to be aware of:

//* Changes to features that are in Technical Preview.
//* Changes to log formats.
//* Changes to non-public APIs.
//* Behaviour changes that repair critical bugs.

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[known-issues-8.7.x]]
//=== Known issues

//[[known-issue-issue#]]
//.Short description
//[%collapsible]
//====

//*Details*

//<Describe known issue.>

//*Impact* +

//<Describe impact or workaround.>

//====

//[discrete]
//[[deprecations-8.7.x]]
//=== Deprecations

//The following functionality is deprecated in 8.7.x, and will be removed in
//8.7.x. Deprecated functionality does not have an immediate impact on your
//application, but we strongly recommend you make the necessary updates after you
//upgrade to 8.7.x.

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[new-features-8.7.x]]
//=== New features

//The 8.7.x release Added the following new and notable features.

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[enhancements-8.7.x]]
//=== Enhancements

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[bug-fixes-8.7.x]]
//=== Bug fixes

//{fleet}::
//* add info

//{agent}::
//* add info

// end 8.7.x relnotes
