// Use these for links to issue and pulls.
:kibana-issue: https://github.com/elastic/kibana/issues/
:kibana-pull: https://github.com/elastic/kibana/pull/
:beats-issue: https://github.com/elastic/beats/issues/
:beats-pull: https://github.com/elastic/beats/pull/
:agent-libs-pull: https://github.com/elastic/elastic-agent-libs/pull/
:agent-issue: https://github.com/elastic/elastic-agent/issues/
:agent-pull: https://github.com/elastic/elastic-agent/pull/
:fleet-server-issue: https://github.com/elastic/fleet-server/issues/
:fleet-server-pull: https://github.com/elastic/fleet-server/pull/

[[release-notes]]
= Release notes

This section summarizes the changes in each release.

* <<release-notes-8.9.2>>
* <<release-notes-8.9.1>>
* <<release-notes-8.9.0>>

Also see:

* {kibana-ref}/release-notes.html[{kib} release notes]
* {beats-ref}/release-notes.html[{beats} release notes]

// begin 8.9.2 relnotes

[[release-notes-8.9.2]]
== {fleet} and {agent} 8.9.2

Review important information about the {fleet} and {agent} 8.9.2 release.

[discrete]
[[known-issues-8.9.2]]
=== Known issues

[[known-issue-3375-v892]]
.PGP key download fails in an air-gapped environment
[%collapsible]
====

*Details*

Starting from version 8.9.0, when {agent} tries to perform an upgrade, it first verifies the binary signature with the key bundled in the agent.
This process has a backup mechanism that will use the key coming from `https://artifacts.elastic.co/GPG-KEY-elastic-agent` instead of the one it already has.

In an air-gapped environment, the agent won't be able to download the remote key and therefore cannot be upgraded. If you're using an air-gapped environment, we recommended waiting for this issue to be resolved before upgrading to 8.9.x or a higher version, to avoid being unable to upgrade.

*Impact* +

For the upgrade to succeed, the agent needs to download the remote key from a server accessible from the air-gapped environment. Two workarounds are available.

_Option 1_

If an HTTP proxy is available to be used by the {agents} in your {fleet}, add the proxy settings using environment variables as explained in <<host-proxy-env-vars,Proxy Server connectivity using default host variables>>.
Please note that you need to enable HTTP Proxy usage for `artifacts.elastic.co` to bypass this problem, so you can craft the `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` environment variables to be used exclusively for it.

_Option 2_

As the upgrade URL is not customizable, we have to "trick" the system by pointing `https://artifacts.elastic.co/` to another host that will have the file.

The following examples require a server in your air-gapped environment that will expose the key you will have downloaded from `https://artifacts.elastic.co/GPG-KEY-elastic-agent``.

*Example 1: Manual*

Edit the {agent} server hosts file to add the following content:

[source,sh]
----
<YOUR_HOST_IP> artifacts.elastic.co
----

The Linux hosts file path is `/etc/hosts`.

Windows hosts file path is `C:\Windows\System32\drivers\etc\hosts`.

*Example 2: Puppet*

[source,yaml]
----
host { 'elastic-artifacts':
  ensure       => 'present'
  comment      => 'Workaround for PGP check'
  ip           => '<YOUR_HOST_IP>'
}
----

*Example 3: Ansible*

[source,yaml]
----
- name  : 'elastic-artifacts'
  hosts : 'all'
  become: 'yes'  

  tasks:
    - name: 'Add entry to /etc/hosts'
      lineinfile:
        path: '/etc/hosts'
        line: '<YOUR_HOST_IP> artifacts.elastic.co'
----

====

[discrete]
[[enhancements-8.9.2]]
=== Enhancements

{fleet}::
* Adds the configuration setting `xpack.fleet.packageVerification.gpgKeyPath` as an environment variable in the {kib} container. {kibana-pull}163783[#163783].

{agent}::
* Adds logging to the restart step of the {agent} upgrade rollback process. {agent-pull}3245[#3245]

[discrete]
[[bug-fixes-8.9.2]]
=== Bug fixes

{agent}::
* Correctly identify retryable errors when attempting to uninstall on Windows. {agent-pull}3317[#3317]

// end 8.9.2 relnotes

// begin 8.9.1 relnotes

[[release-notes-8.9.1]]
== {fleet} and {agent} 8.9.1

Review important information about the {fleet} and {agent} 8.9.1 release.

[discrete]
[[security-updates-8.9.1]]
=== Security updates

{agent}::
* Updated Go version to 1.19.12. {agent-pull}3186[#3186] 

[discrete]
[[known-issues-8.9.1]]
=== Known issues

[[known-issue-3375-v891]]
.PGP key download fails in an air-gapped environment
[%collapsible]
====

*Details*

Starting from version 8.9.0, when {agent} tries to perform an upgrade, it first verifies the binary signature with the key bundled in the agent.
This process has a backup mechanism that will use the key coming from `https://artifacts.elastic.co/GPG-KEY-elastic-agent` instead of the one it already has.

In an air-gapped environment, the agent won't be able to download the remote key and therefore cannot be upgraded. If you're using an air-gapped environment, we recommended waiting for this issue to be resolved before upgrading to 8.9.x or a higher version, to avoid being unable to upgrade.

*Impact* +

For the upgrade to succeed, the agent needs to download the remote key from a server accessible from the air-gapped environment. Two workarounds are available.

_Option 1_

If an HTTP proxy is available to be used by the {agents} in your {fleet}, add the proxy settings using environment variables as explained in <<host-proxy-env-vars,Proxy Server connectivity using default host variables>>.
Please note that you need to enable HTTP Proxy usage for `artifacts.elastic.co` to bypass this problem, so you can craft the `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` environment variables to be used exclusively for it.

_Option 2_

As the upgrade URL is not customizable, we have to "trick" the system by pointing `https://artifacts.elastic.co/` to another host that will have the file.

The following examples require a server in your air-gapped environment that will expose the key you will have downloaded from `https://artifacts.elastic.co/GPG-KEY-elastic-agent``.

*Example 1: Manual*

Edit the {agent} server hosts file to add the following content:

[source,sh]
----
<YOUR_HOST_IP> artifacts.elastic.co
----

The Linux hosts file path is `/etc/hosts`.

Windows hosts file path is `C:\Windows\System32\drivers\etc\hosts`.

*Example 2: Puppet*

[source,yaml]
----
host { 'elastic-artifacts':
  ensure       => 'present'
  comment      => 'Workaround for PGP check'
  ip           => '<YOUR_HOST_IP>'
}
----

*Example 3: Ansible*

[source,yaml]
----
- name  : 'elastic-artifacts'
  hosts : 'all'
  become: 'yes'  

  tasks:
    - name: 'Add entry to /etc/hosts'
      lineinfile:
        path: '/etc/hosts'
        line: '<YOUR_HOST_IP> artifacts.elastic.co'
----

====

[discrete]
[[bug-fixes-8.9.1]]
=== Bug fixes

{fleet}::
* Fixes for query error on Agents list in the UI. ({kibana-pull}162816[#162816])
* Remove duplicate path being pushed to package archive. ({kibana-pull}162724[#162724])

{agent}::
* Improve two unclear error messages in the Upgrade Watcher {agent-pull}3093[#3093]
* Add default UTC timezone to synthetics agent Docker images to prevent navigation errors {agent-pull}3160[#3160] {beats-issue}36117[#36117]

// end 8.9.1 relnotes

// begin 8.9.0 relnotes

[[release-notes-8.9.0]]
== {fleet} and {agent} 8.9.0

Review important information about the {fleet} and {agent} 8.9.0 release.

[discrete]
[[security-updates-8.9.0]]
=== Security updates

{fleet-server}::
* Use a verified base image for building Fleet Server binaries. {fleet-server-pull}2339[#2339]

[discrete]
[[known-issues-8.9.0]]
=== Known issues

[[known-issue-3375]]
.PGP key download fails in an air-gapped environment
[%collapsible]
====

*Details*

Starting from version 8.9.0, when {agent} tries to perform an upgrade, it first verifies the binary signature with the key bundled in the agent.
This process has a backup mechanism that will use the key coming from `https://artifacts.elastic.co/GPG-KEY-elastic-agent` instead of the one it already has.

In an air-gapped environment, the agent won't be able to download the remote key and therefore cannot be upgraded. If you're using an air-gapped environment, we recommended waiting for this issue to be resolved before upgrading to 8.9.x or a higher version, to avoid being unable to upgrade.

*Impact* +

For the upgrade to succeed, the agent needs to download the remote key from a server accessible from the air-gapped environment. Two workarounds are available.

_Option 1_

If an HTTP proxy is available to be used by the {agents} in your {fleet}, add the proxy settings using environment variables as explained in <<host-proxy-env-vars,Proxy Server connectivity using default host variables>>.
Please note that you need to enable HTTP Proxy usage for `artifacts.elastic.co` to bypass this problem, so you can craft the `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` environment variables to be used exclusively for it.

_Option 2_

As the upgrade URL is not customizable, we have to "trick" the system by pointing `https://artifacts.elastic.co/` to another host that will have the file.

The following examples require a server in your air-gapped environment that will expose the key you will have downloaded from `https://artifacts.elastic.co/GPG-KEY-elastic-agent``.

*Example 1: Manual*

Edit the {agent} server hosts file to add the following content:

[source,sh]
----
<YOUR_HOST_IP> artifacts.elastic.co
----

The Linux hosts file path is `/etc/hosts`.

Windows hosts file path is `C:\Windows\System32\drivers\etc\hosts`.

*Example 2: Puppet*

[source,yaml]
----
host { 'elastic-artifacts':
  ensure       => 'present'
  comment      => 'Workaround for PGP check'
  ip           => '<YOUR_HOST_IP>'
}
----

*Example 3: Ansible*

[source,yaml]
----
- name  : 'elastic-artifacts'
  hosts : 'all'
  become: 'yes'  

  tasks:
    - name: 'Add entry to /etc/hosts'
      lineinfile:
        path: '/etc/hosts'
        line: '<YOUR_HOST_IP> artifacts.elastic.co'
----

====

[discrete]
[[breaking-changes-8.9.0]]
=== Breaking changes

Breaking changes can prevent your application from optimal operation and
performance. Before you upgrade, review the breaking changes, then mitigate the
impact to your application.

[discrete]
[[breaking-2890]]
.Status command has been changed.
[%collapsible]
====
*Details* +
The {agent} `status` command has been changed so that the default human output now uses a list format and summaries output.

*Impact* +
Full human output can be obtained with the new `full` option.
For for information, refer to {agent-pull}2890[#2890].
====

[discrete]
[[breaking-2531]]
.API default error code is now 500.
[%collapsible]
====
*Details* +
Previously, when {fleet-server} encountered an unexpected error it resulted in a `Bad Request` response.

*Impact* +
Now, any unexpected error returns an `Internal Server Error` response while keeping most of the current behavior
unchanged. On expected failure paths (for example, Agent Inactive, Missing Agent ID, Missing Auth Header) a `Bad Request` response is returned. For more information, refer to {fleet-server-pull}2531[#2531].
====

[discrete]
[[breaking-ecs-hostname]]
.`host.name` field changed to ECS lowercase format.
[%collapsible]
====
*Details* +
In {agent} output the `host.name` field has been changed to lowercase to match Elastic Common Schema (ECS) guidelines. The agent name is also reported in lowercase (`AGENT-name` becomes `agent-name`).

*Impact* +
After upgrading {agent} to version 8.9.0 or higher, any case-sensitive searches may result in false-positive alerts. For example, a case-sensitive search based on the upper-case `AGENT-name` could result in an alert such as `system.load.1 reported no data in the last 5m for AGENT-name`. After upgrading, you may need to manually clear alerts and adjust some searches to match the new `host.name` format.

====

[discrete]
[[new-features-8.9.0]]
=== New features

The 8.9.0 release Added the following new and notable features.

{fleet}::
* Adds CloudFormation install method to CSPM. {kibana-pull}159994[#159994]
* Adds flags to give permissions to write to any dataset and namespace. {kibana-pull}157897[#157897]
* Disables Agent ID verification for Observability projects. {kibana-pull}157400[#157400]
* Setup `ignore_malformed` in {fleet}. {kibana-pull}157184[#157184]

{fleet-server}::
* A new `elastic-api` version header is added, allow versioning of the {fleet-server} APIs. {fleet-server-pull}2677[#2677]
* Support delivery of user-uploaded files to integrations. {fleet-server-pull}2666[#2666]

{agent}::
* Add the logs subcommand to the agent CLI. {agent-pull}2752[#2745] {agent-issue}114[#114]
* Support upgrading to specific snapshots by specifying the build ID. {agent-pull}2752[#2752]

[discrete]
[[enhancements-8.9.0]]
=== Enhancements

{fleet}::
* Adds agent integration health reporting in the Fleet UI. {kibana-pull}158826[#158826]

{fleet-server}::
* Expose Prometheus metrics on metrics listener (when enabled). Ship Prometheus metrics with apm.Tracer when tracer is enabled. {fleet-server-pull}2610[#2610]


{agent}::
* Add additional elements to support the Universal Profiling integration. {agent-pull}2881[#2881]

[discrete]
[[bug-fixes-8.9.0]]
=== Bug fixes

{fleet}::
* Fixes a bug that prevented `index.mapping` settings to be propagated into component templates from default settings. {kibana-pull}157289[#157289]

{fleet-server}::
* Fixes a bug during {agent} upgrades where `action_seq_no` was overwritten with 0 if the `ackToken` was not provided. {fleet-server-pull}2582[#2582]
* Fixes an issue that caused {fleet-server} to go offline after reboot. {fleet-server-pull}2697[#2697] {fleet-server-pull}2431[#2431]

{agent}::
* Change monitoring socket to use a hash of the ID instead of the actual ID. {agent-pull}2912[#2912]
* Fix the drop processor for monitoring component logs to use the `component.id` instead of the dataset. {agent-pull}2982[#2982] {agent-issue}2388[#2388]
* Update Node version to 18.16.0. {agent-pull}2696[#2696] 

// end 8.9.0 relnotes


// ---------------------
//TEMPLATE
//Use the following text as a template. Remember to replace the version info.

// begin 8.7.x relnotes

//[[release-notes-8.7.x]]
//== {fleet} and {agent} 8.7.x

//Review important information about the {fleet} and {agent} 8.7.x release.

//[discrete]
//[[security-updates-8.7.x]]
//=== Security updates

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[breaking-changes-8.7.x]]
//=== Breaking changes

//Breaking changes can prevent your application from optimal operation and
//performance. Before you upgrade, review the breaking changes, then mitigate the
//impact to your application.

//[discrete]
//[[breaking-PR#]]
//.Short description
//[%collapsible]
//====
//*Details* +
//<Describe new behavior.> For more information, refer to {kibana-pull}PR[#PR].

//*Impact* +
//<Describe how users should mitigate the change.> For more information, refer to {fleet-guide}/fleet-server.html[Fleet Server].
//====

//[discrete]
//[[known-issues-8.7.x]]
//=== Known issues

//[[known-issue-issue#]]
//.Short description
//[%collapsible]
//====

//*Details*

//<Describe known issue.>

//*Impact* +

//<Describe impact or workaround.>

//====

//[discrete]
//[[deprecations-8.7.x]]
//=== Deprecations

//The following functionality is deprecated in 8.7.x, and will be removed in
//8.7.x. Deprecated functionality does not have an immediate impact on your
//application, but we strongly recommend you make the necessary updates after you
//upgrade to 8.7.x.

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[new-features-8.7.x]]
//=== New features

//The 8.7.x release Added the following new and notable features.

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[enhancements-8.7.x]]
//=== Enhancements

//{fleet}::
//* add info

//{agent}::
//* add info

//[discrete]
//[[bug-fixes-8.7.x]]
//=== Bug fixes

//{fleet}::
//* add info

//{agent}::
//* add info

// end 8.7.x relnotes
