[[ls-enrich]]
== 10. {agent} to {ls} (for enrichment) to {es}

Ingest model::
{agent} to {es} using {ls} to enrich the data

Use when::
Data enrichment in {es} is not practical for business or technical reasons

Examples::
* Data sources that change frequently, such as stock ticker data
* Enrichment data is proprietary and cannot be stored elsewhere. 
(In this case, you can insert Logstash between agents and {es}.)

**ToDo** +
Add image: Agent to Logstash to ES showing Logstash reaching out to an external source to collect enrichment data, doing the enrichment and then sending it to ES

[discrete]
[[ls-enrich-resources]]
=== Resources

Info on {agent} and agent integrations:

* {fleet-guide}[Fleet and Elastic Agent Guide]
* {integrations-docs}[{agent} integrations]

For info on {ls} for transformation, check out these sections in the {logstash-ref}[Logstash Reference]:

* {logstash-ref}/transformation.html[Transforming Data] 
* {logstash-ref}/filter-plugins.html[Logstash filter plugins]

