[[enrich-fields]]
== 11. {agent} to {ls} (for enrichment) to {es}: Enrichment based on fields in {agent} data

Ingest model::
{agent} to {ls} for enrichment based on fields to {es}

Use when::
Your use case requires data enrichment based on fields in the {agent} data.
{ls} can collect enrichment data based on those fields, and then send the data to {es}.

Example::
When enrichment is done with an HTTP API whose return depends on values from the document. 
For example, an API that takes geo points with the collected data and returns available real estate in the region, and then passes to {ls} enrichment for enrichment between agents and {es}.

**ToDo** 
Add image: Agent to Logstash to ES showing Logstash reaching out to an external source to collect enrichment data based on fields in agent data, doing the enrichment and then sending it to ES

[discrete]
[[enrich-fields-resources]]
=== Resources

More info on {agent} and agent integrations:

* {fleet-guide}[Fleet and Elastic Agent Guide]
* {integrations-docs}[{agent} integrations]

For more info on {ls} for transformation, check out these sections in the {logstash-ref}[Logstash Reference]:

* {logstash-ref}/transformation.html[Transforming Data] 
* {logstash-ref}/filter-plugins.html[Logstash filter plugins]

