[[ls-multi]]
=== 13. {agent} to {ls} for routing to multiple {es} clusters and/or additional destinations

Ingest model::
{agent} to {ls} to {es} clusters and/or additional destinations

Use when::
Data collected by {agent} needs to be routed to different {es} clusters or non-{es} destinations depending on the content

Example::
Let’s take an example of a Windows workstation, for which we are collecting different types of logs using the System and Windows integrations. 
These logs need to be sent to different {es} clusters and to S3 for backup and a mechanism to send it to other destinations such as different SIEM solutions. In addition, the {es} destination is derived based on the type of datastream and an organization identifier. 
+
In such use cases, agents send the data to {ls} as a routing mechanism to different destinations. 
Note that the System and Windows integrations must be installed on all {es} clusters to which the data is routed.

**ToDo:** 

* Add image showing Agent to LS to [Destination1, Destination2, ..] 
* Add config example/logic in Logstash for routing data to different destinations

[discrete]
[[multi-resources]]
==== Resources

Info on {agent} and agent integrations:

* {fleet-guide}[Fleet and Elastic Agent Guide]
* {integrations-docs}[{agent} integrations]

Info on {ls} and {ls} outputs:

* {logstash-ref}[{ls} Reference] 
* {logstash-ref}/plugins-outputs-elasticsearch.html[{ls} {es} output plugin]
* {logstash-ref}/output-plugins.html[{ls} output plugins]

Info on {es}:

* {ref}[{es} Guide]

