== 13. Multi-tenant/multiple destinations

* Multi-tenant/use case architecture: Agent collected data needs to be routed to different ES clusters or non-ES destinations depending on the content
** Let’s take an example of a windows workstation, for which we are collecting different types of logs using system and windows integration. And these logs need to be sent to different ES clusters and to S3 for backup and a mechanism to send it to other destinations such as different SIEM solutions. In addition, the ES destination is derived based on the type of datastream and an organization identifier. In such use cases, agents send the data to logstash and then logstash can be used as a routing mechanism to send it to different destinations. Note that the system and windows integration needs to be installed on all of these ES clusters to which this data is routed
*** Show the routing architecture (Agent -> LS -> [Destination1, Destination2, ..] ) with real example and the logic in logstash for routing this data to different destinations



