[[agent-custom]]
== 2. {agent} to {es} using a custom integration

TIP: You can host {es} on your own hardware or send your data to {es} on {ecloud}. 
For most users, {agent} writing directly to {es} on {ecloud} provides the easiest and fastest time to value. {ess-leadin-short}

Ingest models::
* Data from syslog server: {integrations-docs}/tcp[TCP logs (custom)] or {integrations-docs}/udp[UDP logs (custom)] to {es}
* Data from scraping an external API: {integrations-docs}/httpjson[API (httpjson)] to {es}
* Data pushed from external API to HTTP endpoint: {integrations-docs}/http_endpoint[Http Endpoint logs (custom)] to {es}
* Data read from disk: Custom logs [category]: {integrations-docs}/log[Logs (custom)] to {es}

Use when::
No dedicated {agent} integration exists, but a customizable integration is available

[discrete]
[[agent-custom-proc]]
==== Process overview

* Find the integration for your custom data source. In {kib},  go to *Management> Integrations*.
* Enable the integration and set up {agent}. 
* Launch discover/dashboard to explore.

For details and next steps, check out the {integrations-docs}[{agent} integrations] docs for your data source.

[discrete]
[[custom-resources]]
=== Resources

Info on {agent} and agent integrations:

* {fleet-guide}[Fleet and Elastic Agent Guide]
* {integrations-docs}[{agent} integrations]
** {integrations-docs}/tcp[Custom TCP Logs]
** {integrations-docs}/udp[Custom UDP Logs]
** {integrations-docs}/httpjson[Custom API (httpjson)]
** {integrations-docs}/http_endpoint[Custom HTTP Endpoint Logs]
** {integrations-docs}/log[Custom Logs]

Scan the list to find all available integrations available. 
If you have a specific integration in mind, use the Search bar at the top of the page to find it quickly. 

Info on {es}:

* {ref}[{es} Guide]

//ToDo: Break out into 4 additional files/topics with expanded descriptions and appropriate architecture diagrams for each. 

