[[use-case-arch]]
== Ingest architectures and use cases

IMPORTANT: The numbers shown in this table correspond to the numbered architectures in the source documents for easier tracking, and will likely be removed before we go live. 
This table may not appear in the finished documentation, certainly not in its current raw form.
But for now, it's helpful for grouping and quantifying work, and for showing the current set of architectures at a glance. 

**Decision tree**

https://www.elastic.co/guide/en/cloud/current/ec-cloud-ingest-data.html#ec-data-ingest-pipeline[Data ingestion pipeline with decision tree]

/////
ToDo: Set up target as a tagged region and it re-use here.
With this approach, we can display the decision tree diagram here w/o requiring user to click a link.
Eventually, we may move original here, but for now it needs to stay in cloud info.  It's getting lots of hits and performing well. 
/////

[cols="50, 50"]
|===
| *Ingest architecture* | *Use when*

| {agent} to {es} 
a| 
* 1) Elastic integration is available
** 1a) Software components with agent installed
** 1b) Software components with APIs for data collection

| {agent} -> Proxy -> {es}
a|
* 15) Agents have network restrictions for connecting outside of agent network


| {agent} -> {ls} -> {es}
a|
* 10+11) {ls} for enrichment between {agent} and {es}
* 12) {ls} persistent queue for buffering (to accomodate network issues and downstream unavailability)
* 14) Agents have network restrictions for connecting outside of agent network
* 13) Agent collected data needs to be routed to different ES clusters or non-ES destinations depending on the content


| {agent} -> {es} with Kafka as middleware message queue
a|
* 16a) Kafka as middleware message queue: Kafka ES sink connector to write from kafka to {es}

* 16b) Kafka as middleware message queue: {ls} to read from Kafka and route to {es}


| {ls} -> {es}
a|
* 8) Data from source that {agent} can't read (such as databases, AWS Kinesis)

|===
