[[elastic-agent-input-configuration]]
= Configure inputs for standalone {agent}s

++++
<titleabbrev>Inputs</titleabbrev>
++++

The `inputs` section of the `elastic-agent.yml` file specifies how {agent} locates and processes input data.

By default {agent} collects system metrics, such as CPU, memory, network, and file system metrics, and sends them to the default output. For example, to define the datastream for `cpu` metrics, this is the configuration:

["source","yaml"]
-----------------------------------------------------------------------
- type: system/metrics <1>
  id: unique-system-metrics-id <2>
  data_stream.namespace: default <3>
  use_output: default <4>
  meta:
    package: <5>
      name: system
      version: 0.10.9
  streams:
    - metricsets: <6>
      - cpu
      data_stream.dataset: system.cpu <7>
    - metricsets:
      - memory
      data_stream.dataset: system.memory
    - metricsets:
      - network
      data_stream.dataset: system.network
    - metricsets:
      - filesystem
      data_stream.dataset: system.filesystem
-----------------------------------------------------------------------

<1> A generic type describing the data.
<2> A unique ID for the input.
<3> A user-defined namespace.
<4> The name of the `output` to use. If not specified, `default` will be used.
<5> Package specification.
<6> Enabled module metricsets.
+
Refer to the {metricbeat} {metricbeat-ref}/metricbeat-module-system.html[System module] for a list of available options. The metricset fields can be configured.
<7> A user-defined dataset. It can contain anything that makes sense to signify the source of the data.
