[[structure-config-file]]
= Structure of a config file

The `elastic-agent.yml` policy file contains all of the settings that determine how {agent} runs. The most important and commonly used settings are described here, including input and output options, providers used for variables and conditional output, security settings, logging options, enabling of special features, and specifications for {agent} upgrades.

An `elastic-agent.yml` file is modular: You can combine input, output, and all other settings to enable the {integrations-docs}[{integrations}] to use with {agent}. Refer to <<create-standalone-agent-policy,Create a standalone {agent} policy>> for the steps to download the settings to use as a starting point, and then refer to the following links for specifics on how to adjust the settings individually as needed. You can also refer to our example: <<example-standalone-monitor-nginx,Use standalone {agent} to monitor nginx>>.

// Coming soon: Add instructions for obtaining cut-and-paste settings from a new tab on each integration landing page.

[discrete]
[[structure-config-file-components]]
== Config file components

The following categories include the most common settings used to configure standalone {agent}. Follow each link for more detail and examples.

<<elastic-agent-input-configuration,Inputs>>::
Specify how {agent} locates and processes input data.

<<providers,Providers>>::
Specify the key-value pairs used for variable substitution and conditionals in {agent} output.

<<elastic-agent-output-configuration,Outputs>>::
Specify where {agent} sends data.

<<elastic-agent-ssl-configuration,SSL/TLS>>::
Configure SSL including SSL protocols and settings for certificates and keys.

<<elastic-agent-standalone-logging-config,Logging>>::
Configure the {agent} logging output.

<<elastic-agent-standalone-feature-flags,Feature flags>>::
Configure any experiemental features in {agent}. These are disabled by default.

<<elastic-agent-standalone-download,Agent download>>::
Specify the location of required artifacts and other settings used for {agent} upgrades.


